webhintio/hint

src/lib/collectors/utils/requester.ts, tests/helpers/test-server.ts, tests/lib/collectors/utils/requester.ts
Fix #260
* Limit the number of redirects.
* Implement timeout
* Tests
=> Improve requester

src/lib/rules/axe/axe.ts
=> Resolve axe from own directory

docs/user-guide/rules/disown-opener.md
`typeof` -> `target`
https://sonarwhal.com/docs/user-guide/rules/disown-opener.html
=> Fix typo in disown-opener.md

tests/helpers/test-server.ts
Opened a separate PR, so this can get merged quicker since it's breaking our build right now.
=> Fix tsc complaining about finding express name.

src/lib/cli.ts, tests/lib/cli.ts
=> New: Propose to create a new config file if it doesn't exist

src/lib/connectors/jsdom/jsdom.ts
=> Fix: Filter out duplicate fetch requests in jsdom

docs/user-guide/connectors/index.md, src/lib/connectors/shared/async-html.ts, src/lib/connectors/shared/remote-debugging-connector.ts, src/lib/utils/location-helpers.ts, tests/lib/connectors/collect.ts, tests/lib/connectors/events.ts, tests/lib/utils/resource-loader.ts
=> Fix: Chrome connector fails to analize tmz.com

README.md, appveyor.yml
=> Chore: Add support for Windows builds via appveyor

src/lib/connectors/debugging-protocol-common/debugging-protocol-connector.ts
=> Fix: Property name for the new tab url.

docs/contributor-guide/connectors/index.md, docs/user-guide/index.md, docs/user-guide/rules/axe.md
Fixed some typos I found while reading the docs as a user, including using real apostrophes instead of the straight quote.
=> Docs: fix some typos found ad hoc

src/lib/rules/no-vulnerable-javascript-libraries/no-vulnerable-javascript-libraries.ts
Same as in `axe`, I think we should catch the error when executing the injected script in `no-vulnerable-javascript-libraries` as well.
Make sure you:
=> Fix: Catch errors in detecting libraries

src/lib/connectors/debugging-protocol-common/debugging-protocol-connector.ts, src/lib/connectors/jsdom/jsdom.ts, src/lib/sonar.ts, tests/lib/connectors/evaluate.ts
=> Fix: Use `rulesTimeout` in `jsdom`'s  `evaluate`

src/lib/rules/html-checker/html-checker.ts, src/lib/rules/ssllabs/ssllabs.ts
Fix an issue where we could get an exception before reaching the
`try/catch` for the `Promise` that communicates with the 3rd party
service.
Make sure you:
=> Fix: Improve third party service integration

docs/user-guide/rules/no-disallowed-headers.md, src/lib/rules/no-disallowed-headers/no-disallowed-headers.ts
=> New: Add HPKP headers in `no-disallowed-headers`

src/lib/utils/resource-loader.ts
=> Fix: Fix load external rules runing tests

docs/contributor-guide/connectors/events.md, src/lib/connectors/debugging-protocol-common/debugging-protocol-connector.ts, src/lib/connectors/jsdom/jsdom.ts, src/lib/types/events.ts
=> New: Add `element` info to `traverse` events

packages/sonarwhal/src/lib/utils/resource-loader.ts
=> Fix: Add path to load external rules

packages/sonarwhal/src/lib/utils/resource-loader.ts
Make sure you:
See discussion in https://github.com/sonarwhal/sonarwhal/pull/849#issuecomment-370842540
=> Fix: Remove `/dist/src/index.js`

packages/sonarwhal/src/lib/cli/options.ts
=> Fix: Remove unused options in cli help

packages/sonarwhal/src/lib/utils/content-type.ts, packages/sonarwhal/src/lib/utils/misc.ts, packages/sonarwhal/tests/lib/utils/content-type.ts
Make sure you:
Change per https://github.com/sonarwhal/sonarwhal/pull/808#issuecomment-372785511
=> New: Define media type for config files

packages/sonarwhal/src/lib/utils/npm.ts, packages/sonarwhal/tests/lib/utils/fixtures/dep-package.json, packages/sonarwhal/tests/lib/utils/fixtures/dev-package.json, packages/sonarwhal/tests/lib/utils/fixtures/invalid.json, packages/sonarwhal/tests/lib/utils/npm.ts
=> Fix: Install packages as devDependencies

packages/rule-meta-theme-color/.npmrc, packages/rule-meta-theme-color/LICENSE.txt, packages/rule-meta-theme-color/README.md, packages/rule-meta-theme-color/package.json, packages/rule-meta-theme-color/src/rule.ts, packages/rule-meta-theme-color/tests/tests.ts, packages/rule-meta-theme-color/tsconfig.json, yarn.lock
Ref: https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color
=> New: Add rule to check the usage of `theme-color` meta tag

packages/parser-babel-config/README.md, packages/parser-babel-config/src/parser.ts, packages/parser-babel-config/src/types.ts, packages/parser-babel-config/tests/tests.ts
=> Remove `not-found` event and added `parse::babel-config::start`

packages/parser-typescript-config/README.md, packages/parser-typescript-config/src/parser.ts, packages/parser-typescript-config/src/types.ts, packages/parser-typescript-config/tests/tests.ts
=> Remove `not-found` event and added `parse::typescript-config::start`

packages/rule-babel-config/README.md, packages/rule-babel-config/docs/is-valid.md, packages/rule-typescript-config/README.md, packages/rule-typescript-config/docs/is-valid.md
=> Chore: Update docs for packages multirules

packages/rule-manifest-app-name/README.md
=> Docs: Add information about Windows/Microsoft Store limits

packages/rule-typescript-config/README.md, packages/rule-typescript-config/docs/no-comments.md, packages/rule-typescript-config/docs/target.md, packages/rule-typescript-config/src/index.ts, packages/rule-typescript-config/src/no-comments.ts, packages/rule-typescript-config/src/target.ts, packages/rule-typescript-config/tests/fixtures/no-comments/invalid/tsconfig.json, packages/rule-typescript-config/tests/fixtures/no-comments/valid/tsconfig.json, packages/rule-typescript-config/tests/fixtures/target/es2015/tsconfig.json, packages/rule-typescript-config/tests/fixtures/target/es2016/tsconfig.json, packages/rule-typescript-config/tests/fixtures/target/es3/tsconfig.json, packages/rule-typescript-config/tests/fixtures/target/es5/tsconfig.json, packages/rule-typescript-config/tests/fixtures/target/esnext/tsconfig.json, packages/rule-typescript-config/tests/fixtures/target/no-target/tsconfig.json, packages/rule-typescript-config/tests/no-comments.ts, packages/rule-typescript-config/tests/target.ts
Make sure you:
This PR adds a couple new rules for TypeScript. Couple things that I'd like to do first this PR is merged:
* Find a better name for the `target` rule
* Complete the `target` support matrix, `browserslist` returns a lot of browsers in some of the queries and this should be more complete
* Maybe add what browser(s) are affecting the `target`? 
In any case, this is ready to start looking in case there's any major change required.
=> TypeScript rules

packages/sonarwhal/src/lib/cli/wizards/new-rule.ts, packages/sonarwhal/src/lib/cli/wizards/shared-templates/package.hbs, packages/sonarwhal/src/lib/cli/wizards/templates/new-rule/readme.md.hbs, packages/sonarwhal/src/lib/cli/wizards/templates/new-rule/rule-doc.hbs, packages/sonarwhal/tests/lib/cli/wizards/new-rule.ts
Make sure you:
This commit update the documentation generated by `new-rule` for
packages mono rule and multi rules.
Fix #1013
=> Chore: Update `new-rule`.

.travis.yml
Make sure you:
Fail node v10 builds because all dependencies have been updated or have binaries available now.
Fix #1027
=> Build: Fail node v10 builds

packages/sonarwhal/src/lib/cli/wizards/new-parser.ts, packages/sonarwhal/src/lib/cli/wizards/new-rule.ts
=> Chore: Make more clear the steps to use the new rule or parser

packages/sonarwhal/docs/contributor-guide/how-to/test-rules.md
=> Fix: Improve "Test a rule" documentation

packages/sonarwhal/src/lib/config/config-schema.json, packages/sonarwhal/tests/lib/config/config-validator.ts
=> Fix: Configuration schema for rules

packages/sonarwhal/docs/user-guide/further-configuration/development-flow.md
Make sure you:
Initial work for #1037.
I'll continue working on other scenarios but this can be merged any time after it passes the review cycle.
=> Docs: Add how to "Test a local server"

packages/rule-babel-config/README.md, packages/rule-babel-config/docs/is-valid.md, packages/rule-https-only/README.md, packages/rule-typescript-config/README.md, packages/rule-typescript-config/docs/consistent-casing.md, packages/rule-typescript-config/docs/import-helpers.md, packages/rule-typescript-config/docs/is-valid.md, packages/rule-typescript-config/docs/no-comments.md, packages/rule-typescript-config/docs/strict.md, packages/rule-typescript-config/docs/target.md, packages/rule-webpack-config/docs/config-exists.md, packages/rule-webpack-config/docs/is-installed.md, packages/rule-webpack-config/docs/is-valid.md, packages/rule-webpack-config/docs/module-esnext-typescript.md, packages/rule-webpack-config/docs/modules-false-babel.md, packages/rule-webpack-config/docs/no-devtool-in-prod.md
=> Fix: Documentation titles

packages/rule-minified-js/README.md
Make sure you:
Fixing the wrong rule name in README code block.
=> Docs: Fixing wrong rule name in readme

packages/sonarwhal/src/lib/cli/analyze.ts
=> Fix: List packages missed or incompatible before install them

packages/sonarwhal/src/lib/config.ts, packages/sonarwhal/src/lib/enums/errorstatus.ts, packages/sonarwhal/src/lib/types/resourceerror.ts, packages/sonarwhal/src/lib/utils/resource-loader.ts
=> Abort sonarwhal execution if a resource dependency is missing

packages/rule-http-compression/README.md
Make sure you:
Fixed spelling of `encodigs` to `encodings`
=> Fix spelling

.github/PULL_REQUEST_TEMPLATE.md
Make sure you:
Fix the URLs in the pull request template
=> Fix URLs in PULL_REQUEST_TEMPLATE.md

packages/rule-minified-js/src/rule.ts
Adding a debug statement to print calculated improvementIndex
for each javascript resource evaluated by the rule
Make sure you:
=> Chore: Adding debug statement

packages/sonarwhal/docs/about/FAQ.md
=> Docs: Add `/` to the scanner link

packages/formatter-html/src/assets/js/scan/scanner-common.js, packages/formatter-html/src/views/partials/scan-result.ejs
=> Fix: Error message on errors and console error

packages/formatter-html/src/assets/js/scan/scanner-common.js
=> Fix: Remove template string from html formatter shared script

packages/hint/package.json, yarn.lock
=> Fix: `@types/sinon` to version `5.0.5` to avoid problems with tests

packages/hint/docs/contributor-guide/getting-started/events.md, packages/hint/docs/contributor-guide/getting-started/pull-requests.md, packages/hint/docs/contributor-guide/how-to/connector.md, packages/hint/docs/user-guide/concepts/connectors.md, packages/hint/docs/user-guide/configuring-webhint/browser-context.md, packages/hint/docs/user-guide/configuring-webhint/website-authentication.md, packages/hint/docs/user-guide/index.md
=> Docs: Fix some links

packages/connector-chrome/README.md, packages/connector-edge/README.md, packages/connector-jsdom/README.md, packages/connector-local/README.md, packages/extension-browser/README.md, packages/extension-vscode/README.md, packages/formatter-codeframe/README.md, packages/formatter-excel/README.md, packages/formatter-html/README.md, packages/formatter-json/README.md, packages/formatter-stylish/README.md, packages/formatter-summary/README.md, packages/parser-babel-config/README.md, packages/parser-css/README.md, packages/parser-html/README.md, packages/parser-javascript/README.md, packages/parser-manifest/README.md, packages/parser-typescript-config/README.md, packages/parser-webpack-config/README.md
=> Docs: Small improvements

packages/hint/src/lib/config/config-schema.json
=> Fix: Hint json schema issue in ignoredUrls property

package.json, scripts/test.js, yarn.lock
Make sure you:
Fix #1637
This is the output when something fails:
This will run the tests up to 3 times (the expected one + 2 retries)
=> Chore: Auto-retry failing tests

README.md
=> New: Add FOSSA

packages/extension-vscode/package.json
Make sure you:
The previous version was causing issues when building with newer vscode
versions. Also the generated output only contains the minimum required
files.
Fix #1541
=> Chore: Update `vscode` `devDependency` and `engine` to latest versions

scripts/release.ts
=> Improve release script

scripts/release.ts
Make sure you:
Ref https://github.com/webhintio/hint/issues/1608#issuecomment-453162165
=> Build: Add `***NO_CI***` to skip Azure Pipelines

packages/connector-jsdom/src/connector.ts
=> Fix: Add mechanism to close subprocesses in Linux for jsdom connector

packages/hint-babel-config/src/is-valid.ts, packages/hint-babel-config/tests/is-valid.ts, packages/hint-manifest-is-valid/src/hint.ts, packages/hint-manifest-is-valid/tests/tests.ts, packages/hint-typescript-config/src/is-valid.ts, packages/hint-typescript-config/tests/is-valid.ts, packages/hint/src/lib/config/config-validator.ts, packages/hint/src/lib/types/problems.ts, packages/hint/src/lib/types/schema-validation-result.ts, packages/hint/src/lib/utils/json-parser.ts, packages/hint/src/lib/utils/schema-validator.ts, packages/hint/tests/lib/utils/schema-validator.ts, packages/parser-babel-config/src/parser.ts, packages/parser-babel-config/src/types.ts, packages/parser-manifest/src/parser.ts, packages/parser-manifest/src/types.ts, packages/parser-manifest/tests/tests.ts, packages/parser-package-json/src/parser.ts, packages/parser-package-json/src/types.ts, packages/parser-typescript-config/src/parser.ts, packages/parser-typescript-config/src/types.ts
Fix #1526
Pending tasks:
Make sure you:
=> Fix: Error returned when the config is invalid.

scripts/release.ts
=> Build: Do not trigger release if only `Docs` changes

package.json, scripts/release.ts, yarn.lock
=> Build: Make release script auto-retry tests if they fail

packages/hint-http-compression/README.md
=> Docs: Add more information related to the `Accept-Encoding` header

tsconfig.json
Make sure you:
Make "Go to Definition" in editors like VS Code take you to the
original `*.ts` file in `src` instead of the `*.d.ts` file in `dist`.
https://www.typescriptlang.org/docs/handbook/project-references.html#declarationmaps
=> Chore: Enable TypeScript declaration maps

packages/parser-css/package.json, packages/parser-css/src/parser.ts, packages/parser-css/tests/basic-tests.ts, packages/parser-css/tests/helpers/mocks.ts, packages/parser-css/tests/interface-tests.ts, yarn.lock
Make sure you:
Fix #1580
Also update tests to run in parallel.
Co-Authored-By: Borja Ruiz Torres <borgitas21@users.noreply.github.com>
=> Fix: Gracefully handle malformed CSS

packages/hint-compat-api/src/core/api-hint.ts, packages/hint-compat-api/src/helpers/compat-css.ts, packages/hint-compat-api/src/helpers/compat-html.ts, packages/hint-compat-api/tests/css-next.ts
Make sure you:
Related with #1766
It should be merged after this PR #1660 is merged.
=> Wrong report message when testing subfeatures with prefix

packages/extension-browser/package.json, packages/extension-browser/src/@types/svg-url-loader.d.ts, packages/extension-browser/src/devtools/panel/views/pages/analyze.ts, packages/extension-browser/webpack.config.js, yarn.lock
[extension-browser-pr-1791.zip](https://github.com/webhintio/hint/files/2810148/extension-browser-pr-1791.zip)
Make sure you:
Inline svgs as data urls using [svg-url-loader](https://github.com/bhovhannes/svg-url-loader) reducing the number of resource requests which should provide a slightly better experience for users.
Bundle for testing:
* [extension-browser-pr-1791.zip](https://github.com/webhintio/hint/files/2810153/extension-browser-pr-1791.zip) (Updated 01/29/2019)
=> Chore: Inline svgs as urls using svg-url-loader

packages/hint-compat-api/src/core/api-hint.ts, packages/hint-compat-api/src/core/deprecated-hint.ts, packages/hint-compat-api/src/core/next-hint.ts, packages/hint-compat-api/src/css-next.ts, packages/hint-compat-api/src/css.ts, packages/hint-compat-api/src/helpers/compat-base.ts, packages/hint-compat-api/src/helpers/compat-css.ts, packages/hint-compat-api/src/helpers/compat-library-factory.ts, packages/hint-compat-api/src/html-next.ts, packages/hint-compat-api/src/html.ts, packages/hint-compat-api/src/types.ts
Make sure you:
After writting down the documentation I realized I could improve a bit the way we were dealing with `CompatCSS` and `CompatHTML` classes. This PR tries to handle it better.
=> Minor code improvement in compat-api Hint

package.json, scripts/test-all.js
Make sure you:
The current `build`  script is a bit naive and doesn't build the dependencies in the right order.
With this change everything is built in the right order.
=> Build: Make `build` script reliable

packages/create-hint/src/shared-templates/package.hbs, packages/create-parser/src/shared-templates/package.hbs
Make sure you:
Update some of the dependencies in the `create-` packages.
=> Chore: Upgrade dependencies in template

packages/hint-babel-config/src/is-valid.ts, packages/hint-babel-config/tests/is-valid.ts, packages/hint-typescript-config/src/is-valid.ts, packages/hint-typescript-config/tests/fixtures/extends-with-error/tsconfig.json, packages/hint-typescript-config/tests/is-valid.ts, packages/hint-typescript-config/tests/no-comments.ts, packages/hint/src/lib/types/parser.ts, packages/hint/src/lib/utils/json-parser.ts, packages/hint/tests/lib/types/parser.ts, packages/parser-babel-config/src/parser.ts, packages/parser-babel-config/src/types.ts, packages/parser-babel-config/tests/tests.ts, packages/parser-typescript-config/src/parser.ts, packages/parser-typescript-config/src/types.ts, packages/parser-typescript-config/tests/tests.ts
=> Fix: Report inherited errors at `extends` location

azure-pipelines/standard.yml
=> Macos chrome

packages/configuration-development/index.json, packages/configuration-development/package.json, packages/configuration-web-recommended/index.json, packages/configuration-web-recommended/package.json, packages/extension-browser/package.json, packages/extension-browser/src/content-script/webhint.ts, packages/hint-css-prefix-order/.npmrc, packages/hint-css-prefix-order/LICENSE.txt, packages/hint-css-prefix-order/README.md, packages/hint-css-prefix-order/package.json, packages/hint-css-prefix-order/src/hint.ts, packages/hint-css-prefix-order/src/meta.ts, packages/hint-css-prefix-order/tests/fixtures/cross-block.css, packages/hint-css-prefix-order/tests/fixtures/interleaved-prefixes.css, packages/hint-css-prefix-order/tests/fixtures/mixed-with-prefixes-first.css, packages/hint-css-prefix-order/tests/fixtures/mixed-with-prefixes-last.css, packages/hint-css-prefix-order/tests/fixtures/multi-block.css, packages/hint-css-prefix-order/tests/fixtures/multi-property.css, packages/hint-css-prefix-order/tests/fixtures/prefixed-only.css, packages/hint-css-prefix-order/tests/fixtures/prefixed-values-first.css, packages/hint-css-prefix-order/tests/fixtures/prefixed-values-last.css, packages/hint-css-prefix-order/tests/fixtures/prefixes-first-same-line.css, packages/hint-css-prefix-order/tests/fixtures/prefixes-first.css, packages/hint-css-prefix-order/tests/fixtures/prefixes-last-moz.css, packages/hint-css-prefix-order/tests/fixtures/prefixes-last-same-line.css, packages/hint-css-prefix-order/tests/fixtures/prefixes-last-webkit.css, packages/hint-css-prefix-order/tests/fixtures/unprefixed-only.css, packages/hint-css-prefix-order/tests/tests.ts, packages/hint-css-prefix-order/tsconfig.json, tsconfig.json
=> New: Hint to validate prefixed CSS properties are listed first

packages/configuration-development/index.json, packages/configuration-development/package.json, packages/configuration-web-recommended/index.json, packages/configuration-web-recommended/package.json, packages/extension-browser/package.json, packages/extension-browser/tsconfig.json, packages/hint-button-type/README.md, packages/hint-button-type/src/meta.ts
=> New: Enable hint-button-type in default configurations

packages/formatter-html/README.md, packages/formatter-html/src/formatter.ts
=> New: Print report output directory

packages/configuration-development/index.json
=> Fix: Development configuration

packages/hint-sri/src/hint.ts, packages/hint-sri/tests/tests-https.ts, packages/hint-sri/tests/tests-local.ts, packages/hint/src/lib/engine.ts, packages/hint/src/lib/hint-context.ts
=> ignoredUrls doesn't work on SRI anymore

packages/hint-compat-api/src/core/api-hint.ts, packages/hint-compat-api/src/helpers/compat-base.ts, packages/hint-compat-api/src/helpers/compat-css.ts, packages/hint-compat-api/src/helpers/compat-html.ts, packages/hint-compat-api/src/helpers/evaluate-query.ts, packages/hint-compat-api/src/types.ts, packages/hint-compat-api/tests/css-next.ts, packages/hint-compat-api/tests/evaluate-query.ts, packages/hint-compat-api/tests/fixtures/css/support-flex.css, yarn.lock
=> Fix: Ignore @support block if @support or feature is not supported

packages/hint-meta-charset-utf-8/package.json, packages/hint-meta-charset-utf-8/src/hint.ts, packages/hint-meta-charset-utf-8/tests/tests.ts, packages/hint-meta-charset-utf-8/tsconfig.json, packages/hint/src/lib/utils/content-type.ts, yarn.lock
Make sure you:
Ref #1499 
Part of the work to reduce bundle size for the browser extension.
Required fixing an issue with recognized types for JavaScript. 
~Also enabled a new test in `hint-meta-charset-utf-8` for reporting
unnecessary XML declarations (previously a TODO).~
(abandoned due to mime-type detection issues)
=> Remove cheerio dependency

packages/hint-compat-api/package.json, packages/hint-compat-api/tests/_ignored-connectors.ts, packages/hint-compat-api/tests/css-next.ts, packages/hint-compat-api/tests/css.ts, packages/hint-compat-api/tests/html-next.ts, packages/hint-compat-api/tests/html.ts
=> Chore: Ignore `chrome` on CI

packages/extension-browser/src/content-script/formatter.ts, packages/extension-browser/src/content-script/webhint.ts, packages/formatter-codeframe/package.json, packages/formatter-codeframe/src/formatter.ts, packages/formatter-codeframe/tests/tests.ts, packages/formatter-excel/src/formatter.ts, packages/formatter-excel/tests/tests.ts, packages/formatter-html/src/formatter.ts, packages/formatter-html/tests/tests.ts, packages/formatter-json/src/formatter.ts, packages/formatter-json/tests/fixtures/list-of-problems.ts, packages/formatter-json/tests/tests.ts, packages/formatter-stylish/package.json, packages/formatter-stylish/src/formatter.ts, packages/formatter-stylish/tests/tests.ts, packages/formatter-summary/src/formatter.ts, packages/formatter-summary/tests/tests.ts, packages/hint/src/lib/cli/analyze.ts, packages/hint/src/lib/cli/options.ts, packages/hint/src/lib/types.ts, packages/hint/src/lib/types/formatters.ts, yarn.lock
=> New: Add parameter to output formatter output to a file

packages/hint-html-checker/package.json, packages/hint-html-checker/src/hint.ts, yarn.lock
=> Fix: Use HTML payload instead of serialized version

packages/hint-html-checker/tsconfig.json, packages/hint-sri/package.json, packages/hint-sri/src/hint.ts, packages/hint/package.json, packages/hint/src/lib/cli/analyze.ts, packages/utils-connector-tools/package.json, packages/utils-connector-tools/src/requester.ts, yarn.lock
Make sure you:
Fix #2098
Attaching the latests `stats.json`
[stats.zip](https://github.com/webhintio/hint/files/3005888/stats.zip) where it doesn't show up
=> Chore: Remove `async` dependency

.gitignore, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, package.json, scripts/ava-cache.js
Make sure you:
Track the `.vscode` folder so the team can share the settings:
* Recommended extensions
* PreLaunchTask to create missing `node_modules/.cache/ava/`
* Debugging tasks
* Enable `ESLint` with TypeScript in the workspace as well as
other formatting options like empty ending line, auto-trim,
etc.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Fix #1887
=> Chore: Add common VS Code settings

packages/hint-compat-api/src/helpers/compat-css.ts
=> Fix: Firefox support by replacing lookbehind regex

packages/hint/src/lib/config.ts, packages/hint/tests/lib/config.ts, packages/hint/tests/lib/fixtures/valid/withtwoextends.json
Fix #2077
Make sure you:
~~- [ ] Added/Updated related documentation.~~
=> Fix: Repeated formatter when extending from several configurations

packages/hint-sri/src/hint.ts
Fix #2068
Make sure you:
~~- [ ] Added/Updated related documentation.~~
~~- [ ] Added/Updated related tests.~~
=> Fix: Add `gzip` option to request to decompress content.

packages/utils-debugging-protocol-common/src/debugging-protocol-connector.ts
Make sure you:
Couple commits to hopefully make things better in macOS (and in general?):
`canvas` 2.4.1 has a problem on macOS where it crashes if an svg does
not have dimensions. This sets the dimensions to 1x1
Fix webhintio#2113
Ref Automattic/node-canvas#1400
On macOS Chrome does not fully exit even if all the tabs are closed.
This causes a timeout when running the tests with `nyc` of about 2
minutes (or if the browser is manually closed). This addresses this
issue.
Because during testing multiple workers are using …
=> Improvements for testing on macOS

README.md
I only fixed a typo error.
Make sure you:
=> [doc] fixed comma seperated string

packages/formatter-codeframe/src/formatter.ts, packages/formatter-html/src/views/partials/scan-result-item.ejs, packages/hint-content-type/src/hint.ts, packages/hint-http-cache/src/hint.ts, packages/hint-http-compression/src/hint.ts, packages/hint-no-disallowed-headers/src/hint.ts, packages/hint/src/lib/engine.ts, packages/hint/src/lib/hint-context.ts, packages/hint/src/lib/types/problems.ts, packages/utils/src/network/capitalize-header-name.ts, packages/utils/src/network/index.ts, packages/utils/tests/network/capitalize-header-name.ts
=> Fix: Error location for HTTP headers and added code snippet.

packages/extension-browser/package.json, packages/extension-browser/src/devtools/utils/analytics.ts, yarn.lock
Make sure you:
Fix #2230
Also switch to using the "basic" v2 version of Application Insights.
Raising the bundle size limit by 10KB to account for the additional code. I'll lower this again after #2097.
=> Chore: Inline analytics script

packages/utils-tests-helpers/src/hint-runner.ts
=> Chore: Properly close resources on failure

scripts/check-commit-message.js
=> Docs: Fix broken link to commit style guide

packages/extension-browser/src/manifest.json
No longer needed now that Application Insights is fully bundled.
Make sure you:
=> Chore: Remove CSP from browser extension

packages/hint-manifest-icons/src/meta.ts
=> Chore: Change scope to site

packages/hint/src/lib/engine.ts, packages/hint/src/lib/hint-context.ts, packages/hint/tests/lib/engine.ts
=> Breaking: Refactor `engine.report` to take a `Problem` object

packages/configuration-progressive-web-apps/README.md, packages/configuration-progressive-web-apps/index.json, packages/configuration-progressive-web-apps/package.json
Make sure you:
Did the changes in the `index.json` and README but left `package.json` as the `manifest-icons` is not yet published.
Fixes #2352
=> Update: Add manifest-icons to config-pwa

packages/extension-browser/src/_locales/en/messages.json, packages/formatter-html/src/formatter.ts, packages/utils/src/types/category.ts
=> Drop interoperability category

packages/parser-manifest/src/types.ts
Make sure you:
Another case where #1594 would be useful, but just fixing the bug for now.
=> Fix: Type definition for `ManifestPlatform` to be a string

packages/utils/src/dom/find-original-element.ts, packages/utils/src/dom/html.ts
Make sure you:
Intended to be kept as two separate commits.
=> Fix handling of malformed selectors and missing element IDs

packages/extension-vscode/src/server.ts, packages/extension-vscode/tests/fixtures/mocks.ts, packages/extension-vscode/tests/server.ts, packages/utils/src/has-yarnlock.ts, packages/utils/src/index.ts, packages/utils/src/npm.ts, packages/utils/tests/has-yarnlock.ts, packages/utils/tests/npm.ts
Make sure you:
Detects `yarn.lock` and uses `yarn` to install the missing hint packages in the `.hintrc` 
Resolves #1630
=> Build: Support yarn for installing .hintrc packages

packages/extension-browser/CONTRIBUTING.md
Make sure you:
List build/test steps, describe high-level architecture, detail how to
work with multiple design systems, and explain how to include new
hints and parsers.
Fix #2456
=> Docs: Add CONTRIBUTING.md to extension-browser

packages/extension-browser/src/content-script/connector.ts, packages/extension-browser/src/content-script/webhint.ts, packages/extension-browser/src/devtools/utils/analytics.ts, packages/extension-browser/src/devtools/utils/network.ts, packages/extension-browser/src/devtools/views/app.tsx, packages/extension-browser/src/devtools/views/pages/analyze.tsx, packages/extension-browser/src/devtools/views/pages/config/sections/resources.tsx, packages/hint/src/lib/engine.ts, packages/utils/src/app-insights.ts
=> Fix: Better error handling

azure-pipelines/full.yml, azure-pipelines/standard.yml
=> Build: Update installation of Chrome version

packages/connector-chrome/README.md, packages/connector-jsdom/README.md, packages/connector-local/README.md, packages/connector-puppeteer/README.md, packages/hint/docs/user-guide/concepts/connectors.md
Make sure you:
Fix #2471
Fix #2252
=> Docs: Update connector's options

scripts/update-tsconfig-references.ts
=> Fix: Issue updating references

packages/extension-browser/src/devtools/views/pages/results/hint.css
=> Fix: Hit area for toggle in browser extension result

azure-pipelines/all-versions.yml, azure-pipelines/latest-version.yml
Make sure you:
Use node 12 on Azure Pipelines
=> Build: Use node 12.x instead of 11.x

azure-pipelines/full.yml, azure-pipelines/standard.yml
=> Build: Update Chrome install on Windows

packages/parser-javascript/src/parser.ts, packages/parser-javascript/tests/tests.ts
=> Fix: Parser javascript walk.full/fullAncestor

packages/hint-compat-api/src/css.ts, packages/hint-content-type/src/hint.ts, packages/hint-css-prefix-order/src/hint.ts, packages/hint-highest-available-document-mode/src/hint.ts, packages/hint-html-checker/src/hint.ts, packages/hint-http-cache/src/hint.ts, packages/hint-http-compression/src/hint.ts, packages/hint-no-disallowed-headers/src/hint.ts, packages/hint-no-p3p/src/hint.ts, packages/hint-strict-transport-security/src/hint.ts, packages/hint-validate-set-cookie-header/src/hint.ts, packages/hint-x-content-type-options/src/hint.ts, packages/hint/src/lib/hint-context.ts
=> Fix: Add code language to all hints which report a code snippet

packages/utils/src/report/get-css-code-snippet.ts, packages/utils/tests/fixtures/report.css, packages/utils/tests/report/get-css-code-snippet.ts
=> Fix: Improve formatting for CSS code snippets

packages/hint/docs/user-guide/concepts/connectors.md
=> Docs: Fix links and added connectos to concepts/connectors

packages/extension-browser/src/devtools/views/pages/results/header.css, packages/extension-browser/src/devtools/views/pages/results/header.tsx
=> Fix: Toggle on results page

packages/hint/docs/contributor-guide/how-to/configuration.md, packages/hint/docs/user-guide/concepts/configurations.md
Make sure you:
Clarifies how to use a custom configuration. I don't know how, exactly, accurate this is, but it is the only way I was able to get mine to work. It does not answer the question of namespaced custom configs, which mine surely will be when it's actually published.
Fix #2637
=> Docs: Clarify custom configuration process

README.md
Make sure you:
Add hint configuration in readme.md file
=> Docs: Add hint configuration steps in README

packages/create-hintrc/package.json, packages/extension-browser/.hintrc, packages/extension-browser/package.json, packages/extension-browser/src/_locales/en/messages.json, packages/extension-browser/src/devtools/utils/ids.ts, packages/extension-browser/src/devtools/views/pages/analyze.tsx, packages/extension-browser/src/devtools/views/pages/config.tsx, packages/extension-browser/src/devtools/views/pages/config/example.tsx, packages/extension-browser/src/devtools/views/pages/config/header.css, packages/extension-browser/src/devtools/views/pages/config/header.tsx, packages/extension-browser/src/devtools/views/pages/config/section.tsx, packages/extension-browser/src/devtools/views/pages/config/sections/browsers.tsx, packages/extension-browser/src/devtools/views/pages/config/sections/resources.tsx, packages/extension-browser/src/devtools/views/pages/error.css, packages/extension-browser/src/devtools/views/pages/error.tsx, packages/extension-browser/src/devtools/views/pages/results.css, packages/extension-browser/src/devtools/views/pages/results.tsx, packages/extension-browser/src/devtools/views/pages/results/header.tsx, packages/extension-browser/tests/webhint.ts, packages/hint/package.json, yarn.lock
Make sure you:
Turn on disabled accessibility tests in axe and fix reported issues.
=> Fix browser extension accessibility issues

packages/extension-browser/src/devtools/views/controls/label.css, packages/hint-compat-api/docs/css.md, packages/hint-compat-api/docs/html.md, packages/hint-compat-api/src/css.ts, packages/hint-compat-api/src/html.ts, packages/hint-compat-api/src/utils/browsers.ts
Make sure you:
Making a few final tweaks before the next release.
=> Fix minor issues affecting the browser extension

packages/extension-browser/package.json, packages/extension-browser/src/devtools/utils/analytics.ts, packages/extension-browser/src/devtools/utils/hints.ts, packages/extension-browser/src/devtools/utils/storage.ts, packages/extension-browser/src/devtools/views/app.tsx, packages/extension-browser/src/devtools/views/pages/config.tsx, packages/extension-browser/tests/devtools/utils/hints.ts
=> Track pass/fail/fix status of hints

packages/extension-browser/src/devtools/views/controls/toggle.tsx
=> Fix: `Props` Type for `Toggle` control

packages/extension-browser/src/devtools/utils/hints.ts, packages/extension-browser/tests/devtools/utils/hints.ts
Tracks progress partially fixing issues reported by a hint.
Fix #2678
Make sure you:
=> New: Add fixing state to hint status metrics

release/lib/git-helpers.ts, yarn.lock
=> Fix: Update octokit

packages/extension-browser/src/devtools/views/controls/inspect-button.tsx
=> New: Clicking `Inspect Element` scrolls element into the view

packages/extension-vscode/src/server.ts
The recommended way to install webhint is locally with a project so we
should stop asking the user to install globally.
Fix #2707
Test package for side-loading into VS Code:
* [vscode-webhint-1.0.5.zip](https://github.com/webhintio/hint/files/3436762/vscode-webhint-1.0.5.zip)
To side-load:
* Unzip the linked file to get `vscode-webhint-1.0.5.vsix`
* Go to `View > Extensions`.
* Click `...` in the top-right of the panel.
* Click `Install from VSIX...`.
* Choose the generated `*.vsix` package from disk.
NOTE: Make sure you open a file in the launched vscode instance
that webhint is registered for (like html or tsconfig.json), otherwise,
the server won't start.
Make sure you:
=> Fix: Remove option to add webhint globally

packages/configuration-development/index.json, packages/hint-webpack-config/docs/module-esnext-typescript.md, packages/hint-webpack-config/docs/modules-false-babel.md, packages/hint-webpack-config/src/_locales/en/messages.json, packages/hint-webpack-config/src/module-esnext-typescript.ts, packages/hint-webpack-config/src/modules-false-babel.ts, packages/hint-webpack-config/tests/module-esnext-typescript.ts, packages/hint-webpack-config/tests/modules-false-babel.ts
=> Fix bogus webpack errors

packages/hint-doctype/README.md, packages/hint-image-optimization-cloudinary/README.md
=> Fix: Broken links in documentation

README.md, packages/hint/docs/about/FAQ.md, packages/hint/docs/contributor-guide/how-to/hint.md
Make sure you:
- ~~[ ] Added/Updated related documentation.~~
- ~~[ ] Added/Updated related tests.~~
Updating some missing information found while going through docs. Like:
* Add new categories of hint - development and pitfalls
* Typo fixes
* Fix broken links in FAQ
=> Docs: Update readme and docs with missing information

packages/hint/package.json, packages/hint/src/lib/utils/resource-loader.ts, packages/hint/tests/lib/utils/fixtures/@example/webhint-configuration-example/index.json, packages/hint/tests/lib/utils/fixtures/@example/webhint-configuration-example/package.json, packages/hint/tests/lib/utils/fixtures/@example/webhint-configuration-example/test_modules/@example/webhint-hint-example/index.js, packages/hint/tests/lib/utils/fixtures/@example/webhint-configuration-example/test_modules/@example/webhint-hint-example/package.json, packages/hint/tests/lib/utils/fixtures/@example/webhint-configuration-example/test_modules/@example2/webhint-hint-example2/index.js, packages/hint/tests/lib/utils/fixtures/@example/webhint-configuration-example/test_modules/@example2/webhint-hint-example2/package.json, packages/hint/tests/lib/utils/fixtures/@example/webhint-configuration-example/test_modules/webhint-hint-example3/index.js, packages/hint/tests/lib/utils/fixtures/@example/webhint-configuration-example/test_modules/webhint-hint-example3/package.json, packages/hint/tests/lib/utils/resource-loader.ts, yarn.lock
=> Improve configuration loading

.github/ISSUE_TEMPLATE/2-bug-report-browser.md, package.json, packages/configuration-all/README.md, packages/extension-browser/src/devtools/utils/categories.ts, packages/extension-browser/src/devtools/views/app.tsx, packages/extension-browser/src/devtools/views/controls/feedback-link.tsx, packages/extension-browser/src/devtools/views/pages/config.tsx, packages/extension-browser/src/devtools/views/pages/config/header.tsx, packages/extension-browser/src/devtools/views/pages/config/sections/categories.tsx, packages/extension-browser/src/devtools/views/pages/error.tsx, packages/extension-browser/src/devtools/views/pages/results.tsx, packages/extension-browser/src/devtools/views/pages/results/header.tsx, packages/extension-browser/tests/devtools.ts, packages/extension-browser/tests/fixtures/mock-extension-apis.js, packages/extension-browser/webpack.config.js
=> Fix: Pre-populate known environment data when clicking "Feedback"

packages/extension-vscode/src/extension.ts, packages/extension-vscode/src/notifications.ts, packages/extension-vscode/src/server.ts
Replaces the "Learn More" button with a much simpler link approach.
Also updates button text to make actions clearer.
Make sure you:
=> Fix: Show a link for more information about enabling telemetry

azure-pipelines/all-versions.yml, azure-pipelines/latest-version.yml
This reverts commit 3ab9b9af3649758e3e27bb8478a6ba75b96c60b1.
Fix #2576
Make sure you:
=> Build: Re-enable using node 12.x instead of 11.x in CI

packages/create-hint/src/create-hint.ts, packages/create-hint/src/shared-templates/package.hbs, packages/create-hint/src/templates/hint.ts.hbs, packages/create-hint/src/templates/locales-messages.json.hbs, packages/create-hint/src/templates/meta.ts.hbs, packages/create-hint/src/templates/partial-event-code.hbs, packages/create-hint/tests/create-hint.ts, packages/create-hint/tsconfig.json, packages/hint/docs/contributor-guide/guides/create-custom-hint.md
Make sure you:
Added localization support to `create-hint` package.
Now if new hint is create in main repo (is official), it will have all necessary `i18n` scripts and files.
* `meta` will have `getDescription` and `getName` method
* `_locale` folder will get created with hint `description` and `name` for `en` language.
=> Feat: Added localization support to create-hint package.

packages/hint-http-cache/README.md, packages/hint-image-optimization-cloudinary/README.md
=> Docs: Update outdated HTTP Archive links

packages/extension-browser/src/shims/get-message.ts, packages/extension-browser/webpack.config.js, packages/utils/src/i18n/get-message.ts, packages/utils/tests/i18n/get-message.ts, scripts/create-i18n.js
=> Breaking: Fix localization

release/tasks/calculate-new-versions.ts
=> New: Release script publish packages with docs only changes

release/tasks/update-configuration-all.ts
=> Fix: Add configurations to configuration-all

packages/create-hint/src/shared-templates/package.hbs, packages/hint-axe/package.json, packages/hint-babel-config/package.json, packages/hint-compat-api/package.json, packages/hint-typescript-config/package.json, packages/hint-webpack-config/package.json
=> Fix: Docs not published in multi-hint packages

packages/utils/src/packages/load-hint-package.ts
=> Fix: Error building create-hint release package

packages/extension-browser/src/devtools/views/app.base.css, packages/extension-browser/src/devtools/views/controls/summary.css, packages/extension-browser/src/devtools/views/pages/analyze.css, packages/extension-browser/src/devtools/views/pages/results/header.css, packages/extension-browser/src/devtools/views/pages/results/header.tsx
Make sure you:
I feel that to make UI responsive to all widths, we may need to re design it a bit.
In this PR, I set min-width of root div to `240px` so that buttons and text remain in same line. It also makes screen scroll-able horizontally. 
Please check below screenshots and let me know if it is good or not :)
**Note: ** categories names are not coming as I didn't make release. Instead I loaded it directly from build folder.
For Analyze page, I made logo to come down instead of right side to fit the screen width.
Working on result screen... Till then please let me know if above designs will work or need to have any change.
Fix: #2593
=> Fix css issues in browser extension for small screens

packages/connector-puppeteer/package.json
=> Fix: Dependencies

packages/connector-jsdom/src/connector.ts, packages/connector-puppeteer/src/connector.ts, packages/connector-puppeteer/src/lib/get-favicon.ts, packages/hint-apple-touch-icons/src/hint.ts, packages/parser-manifest/src/parser.ts, packages/parser-manifest/tests/tests.ts, packages/utils-debugging-protocol-common/src/debugging-protocol-connector.ts
=> Fix: Favicon url when a base element is present.

packages/hint/docs/contributor-guide/how-to/formatter.md
Make sure you:
- ~~[ ] Added/Updated related documentation.~~
- ~~[ ] Added/Updated related tests.~~
`formatterOptions` example is updated and some minor text fixes are also done.
Fix: #2820
=> Docs: Update `formatterOptions` in `formatter` documentation

packages/hint/src/bin/hint.ts, packages/utils/src/app-insights.ts
=> Fix: Parameter isAppCrashing in sendPendingData defaults to false

.vscode/extensions.json
Adding since a few members of the team have been interested.
Make sure you:
=> Chore: Include gitlens in recommended VS Code environment

packages/hint-compat-api/docs/html.md, packages/hint-compat-api/src/html.ts
This is used for progressive enhancement and should not be reported.
Fix #2897
Make sure you:
=> Fix: Add link[rel=preload] to the default ignore list

packages/configuration-development/index.json, packages/configuration-development/package.json, packages/configuration-web-recommended/index.json, packages/configuration-web-recommended/package.json
=> New: Enable compat hints in default configurations

packages/hint-http-cache/src/hint.ts, packages/hint-http-cache/tests/tests.ts
=> Fix: Issue with directives and trailing commas

packages/connector-puppeteer/README.md, packages/connector-puppeteer/src/connector.ts, packages/connector-puppeteer/tests/authentication.ts
Make sure you:
Add new property `next` to the connector configuration to allow
multi-step authentication scenarios like the one in Azure Pipelines.
Fix #2834
=> New: Add support for multi-step authentication

packages/configuration-development/index.json, packages/configuration-development/package.json, packages/extension-vscode/package.json, packages/extension-vscode/src/extension.ts, packages/parser-sass/LICENSE.txt, packages/parser-sass/README.md, packages/parser-sass/package.json, packages/parser-sass/src/parser.ts, packages/parser-sass/tests/basic-tests.ts, packages/parser-sass/tests/helpers/mocks.ts, packages/parser-sass/tests/interface-tests.ts, packages/parser-sass/tsconfig.json, tsconfig.json, yarn.lock
=> New: Add parser for SASS and SCSS files

packages/configuration-development/index.json, packages/configuration-development/package.json, packages/extension-vscode/package.json, packages/parser-less/LICENSE.txt, packages/parser-less/README.md, packages/parser-less/package.json, packages/parser-less/src/parser.ts, packages/parser-less/tests/basic-tests.ts, packages/parser-less/tests/fixtures/test.less, packages/parser-less/tests/helpers/mocks.ts, packages/parser-less/tests/interface-tests.ts, packages/parser-less/tsconfig.json, tsconfig.json, yarn.lock
=> New: Add parser for LESS files

packages/extension-vscode/src/extension.ts, packages/extension-vscode/src/server.ts, packages/extension-vscode/src/utils/analytics.ts, packages/extension-vscode/tests/utils/analytics.ts
Aligns with behavior in the browser extension.
Make sure you:
=> New: Log when opting in to telemetry for the first time

packages/extension-vscode/CONTRIBUTING.md, packages/extension-vscode/package.json, release/lib/skippers.ts, release/main.ts, release/tasks/release.ts, release/tasks/validate-environment.ts
=> Publish VS Code extension as part of release script

packages/extension-browser/src/content-script/connector.ts
=> Fix: Fail fast for CSP errors in Firefox

packages/extension-browser/src/content-script/connector.ts
=> Fix: Ignore resources from other extensions

packages/extension-vscode/package.json, packages/extension-vscode/scripts/bundle-size.js, packages/extension-vscode/scripts/tsconfig.json
=> Chore: Validate size of VS Code extension bundle

.vscode/extensions.json
Editorconfig is awesome. Recommend users install the extension to help keep code style consistent.
REF: https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
=> Recommend EditorConfig via extensions.json

packages/extension-vscode/src/utils/analytics.ts, packages/extension-vscode/tests/utils/analytics.ts
=> New: Log file extension in telemetry

packages/hint-compat-api/src/_locales/en/messages.json, packages/hint-compat-api/src/css.ts, packages/hint-compat-api/src/utils/alternatives.ts, packages/hint-compat-api/src/utils/browsers.ts, packages/hint-compat-api/tests/css.ts, packages/hint-compat-api/tests/html.ts, packages/hint-compat-api/tests/utils/browsers.ts, packages/utils/src/compat/browsers.ts, packages/utils/src/compat/css.ts, packages/utils/src/compat/helpers.ts, packages/utils/src/compat/html.ts, packages/utils/tests/compat/browsers.ts
=> New: Suggest alternate support when available

packages/connector-puppeteer/package.json
=> Fix: Test coverage

packages/hint/src/lib/analyzer.ts, packages/hint/tests/lib/analyzer.ts
=> New: Add 'close' to Node API.

packages/connector-puppeteer/README.md
Make sure you:
It didn't work for me on the latest version when it was lower case.
=> Docs: Fix browser option in connector-puppeteer

packages/utils/src/dom/get-element-by-url.ts, packages/utils/src/dom/html.ts
Make sure you:
I've notice that this function is hot while scanning https://www.theguardian.com/international.
See the attached profile (search for `getElementByUrl`
in the Stack Chart tab)).
https://profiler.firefox.com/public/0630a907f132fea1773f16909ca659fb1172b3ae/stack-chart/?globalTrackOrder=9-10-0-1-2-3-4-5-6-7-8&hiddenGlobalTracks=1-2-3-5-0-4-10-9-6-7&implementation=js&localTrackOrderByPid=15967-1-2-0~16415-0~19009-0~16503-0~16439-1-0~18110-0~16624-0-1~16559-0-1~18576-0-1~&search=getElementByUrl&thread=10&v=4
The attached image shows the profile before this change (captured from the Firefox Addon). ~I can't provide a profile taken after this change since I wasn't able to find information about running the extension locally.~ …
=> Fix: Improve performance of getElementByUrl

packages/connector-puppeteer/README.md, packages/connector-puppeteer/package.json, packages/connector-puppeteer/src/connector.ts, packages/connector-puppeteer/src/lib/actions.ts, packages/connector-puppeteer/src/lib/authenticators.ts, packages/connector-puppeteer/src/lib/lifecycle.ts, packages/connector-puppeteer/src/lib/schema.ts, packages/connector-puppeteer/tests/actions.ts, packages/connector-puppeteer/tests/fixtures/action.js, packages/connector-puppeteer/tests/fixtures/invalid-action.js
Make sure you:
Allow users to execute actions before or after navigating to the target
URL.
Fix #2249
Fix #3019
=> New: Add "user actions"

packages/extension-browser/package.json, packages/extension-browser/src/devtools/utils/activity.ts, packages/extension-browser/src/devtools/utils/analytics.ts, packages/extension-browser/tests/devtools/utils/activity.ts, packages/hint/docs/user-guide/telemetry/summary.md
=>  New: Report active days in a rolling 28-day period

scripts/dist-management/pack-and-upload.sh
Make sure you:
Fix issue with not all artifacts being uploaded.
Rel: https://github.com/webhintio/hint/issues/3059#issuecomment-541663585
=> Build: Fix artifact matching pattern

packages/utils-create-server/package.json, scripts/lint-dependencies.js
Make sure you:
Remove unused dependencies.
=> Chore: Remove unused dependencies

packages/hint-typescript-config/tests/fixtures/no-compiler-options/tsconfig.json, packages/hint-typescript-config/tests/no-comments.ts, packages/utils/src/json-parser.ts
Fix #2222
Fix #2037
Make sure you:
=> Fix: Location for json errors

packages/extension-browser/package.json
=> Chore: Allow build-release to work if build hasn't been run yet

packages/hint/docs/user-guide/troubleshoot/summary.md
Adding some information about running webhint on WSL. Feel free to reword, rearrange or review grammar and syntax, English is not my first language and I still have problems redacting in the best way.
Note: I did a mess with the previous PR #3144 , so I'm recreating that again.
=> Adding information about WSL

packages/extension-vscode/src/utils/problems.ts, packages/extension-vscode/tests/utils/problems.ts, packages/hint-compat-api/src/css.ts, packages/hint-compat-api/tests/css.ts, packages/hint-css-prefix-order/src/hint.ts, packages/hint-css-prefix-order/tests/tests.ts, packages/hint-scoped-svg-styles/package.json, packages/hint-scoped-svg-styles/src/hint.ts, packages/utils-tests-helpers/src/hint-runner.ts, packages/utils-tests-helpers/src/hint-test-type.ts, packages/utils/src/report/get-css-location-from-node.ts, packages/utils/src/report/index.ts, packages/utils/src/types/problem-location.ts, packages/utils/tests/report/get-css-location-from-node.ts
=> Fix: Allow ranged location in css.

packages/configuration-development/index.json, packages/configuration-development/package.json, packages/extension-vscode/package.json, packages/parser-javascript/src/walk.ts, packages/parser-typescript/.npmrc, packages/parser-typescript/LICENSE.txt, packages/parser-typescript/README.md, packages/parser-typescript/package.json, packages/parser-typescript/src/parser.ts, packages/parser-typescript/tests/tests.ts, packages/parser-typescript/tsconfig.json, packages/utils/src/content-type.ts, tsconfig.json, yarn.lock
Make sure you:
* Allow existing JS hints to run against *.ts and *.tsx files
* Allow existing HTML hints to run against TSX content
Fix #2888
=> New: Add parser for TypeScript and TSX files

packages/parser-jsx/src/parser.ts, packages/parser-jsx/tests/tests.ts
=> Fix: Map className and htmlFor attributes correctly

packages/parser-typescript/src/parser.ts, packages/parser-typescript/tests/tests.ts
=> Fix: Handle ClassProperty and ignored node types

packages/hint-validate-set-cookie-header/src/hint.ts, packages/hint-validate-set-cookie-header/tests/tests.ts
=> New: Default severity for `validate-set-cookie-header`

packages/hint-typescript-config/src/consistent-casing.ts, packages/hint-typescript-config/src/helpers/config-checker.ts, packages/hint-typescript-config/src/import-helpers.ts, packages/hint-typescript-config/src/is-valid.ts, packages/hint-typescript-config/src/no-comments.ts, packages/hint-typescript-config/src/strict.ts, packages/hint-typescript-config/src/target.ts, packages/hint-typescript-config/tests/consistent-casing.ts, packages/hint-typescript-config/tests/import-helpers.ts, packages/hint-typescript-config/tests/is-valid.ts, packages/hint-typescript-config/tests/no-comments.ts, packages/hint-typescript-config/tests/strict.ts, packages/hint-typescript-config/tests/target.ts
=> New: Default severity for `hint-typescript-config`

packages/hint-meta-viewport/src/hint.ts, packages/hint-meta-viewport/tests/tests.ts
=> New: Default severity for `hint-meta-viewport`

packages/hint-compat-api/src/css.ts, packages/hint-compat-api/src/html.ts, packages/hint-compat-api/tests/css.ts, packages/hint-compat-api/tests/html.ts
=> New: Default severity for `hint-compat-api`

packages/hint-stylesheet-limits/src/hint.ts, packages/hint-stylesheet-limits/tests/tests.ts
Make sure you:
Fix #3249
It has the same commits as #3260 to keep doing some progress
=> New: Default severity for hint-stlysheet limits

packages/hint-amp-validator/src/hint.ts, packages/hint-amp-validator/tests/tests.ts
=> Fix: Default severity for `@hint/hint-amp-validator`

packages/hint-https-only/src/hint.ts, packages/hint-https-only/tests/tests-https.ts, packages/hint-https-only/tests/tests.ts
=> New: Default severity for `https-only`

packages/hint-summary-display/src/hint.ts, packages/hint-summary-display/tests/tests.ts
=> New: Default severity for `summary-display`

packages/hint-http-cache/src/hint.ts, packages/hint-http-cache/tests/tests.ts
=> New: Default severity for `http-cache`

packages/hint-performance-budget/src/_locales/en/messages.json, packages/hint-performance-budget/src/hint.ts, packages/hint-performance-budget/tests/tests-http.ts, packages/hint-performance-budget/tests/tests-https.ts
=> Fix: Default severity for `@hint/hint-performance-budget`

packages/hint-meta-charset-utf-8/src/hint.ts, packages/hint-meta-charset-utf-8/tests/tests.ts, packages/utils-dom/src/htmlelement.ts, packages/utils-types/src/problem-location.ts
=> New: Add default severity to reports hint-meta-charset-utf-8

azure-pipelines/all-versions.yml
=> Fix: Remove node 8 from azure pipelines

packages/hint-http-cache/src/hint.ts, packages/hint/src/lib/hint-context.ts, packages/hint/tests/lib/hint-context.ts
Make sure you:
Need to make Severity mandatory to make sure there's a default one.
Opening as draft until I catch all the bugs
=> New: Make `Severity` mandatory

.vscode/launch.json, release/@types/custom.ts, release/lib/skippers.ts, release/lib/yargs-config.ts, release/main.ts, release/tasks/validate-environment.ts
=> Build: Add `testMode` to release

packages/hint/src/lib/config/config-schema.json, packages/parser-babel-config/src/schema.json, packages/parser-manifest/src/schema.json, packages/parser-package-json/src/schema.json, packages/parser-typescript-config/src/schema.json, packages/parser-typescript-config/tests/fixtures/schema.json, packages/utils-json/src/schema-validator.ts, packages/utils-json/tests/schema-validator.ts, packages/utils/src/config/normalize-hints.ts, packages/utils/src/config/to-absolute-paths.ts, packages/utils/src/types/config.ts
=> Fix: Schema and Types for hints

packages/extension-browser/src/devtools/views/app.fluent.css, packages/extension-browser/src/devtools/views/app.photon.css, packages/extension-browser/src/devtools/views/controls/source-code.css
Fix #3270
Make sure you:
Here are the extensions for self hosting:
Chromium:
[webhint-1.2.1.zip](https://github.com/webhintio/hint/files/3853641/webhint-1.2.1.zip)
Firefox:
[webhint-1.2.1.zip](https://github.com/webhintio/hint/files/3853642/webhint-1.2.1.zip)
=> Fix: Syntax highlighting color incorrect for Edge

packages/configuration-development/package.json, packages/configuration-web-recommended/package.json
=> New: Add formatter-json to default configs

packages/extension-browser/src/devtools/views/pages/results/message-group.css
Make sure you:
For selfhosting:
Chromium: 
[webhint-1.2.1.zip](https://github.com/webhintio/hint/files/3871933/webhint-1.2.1.zip)
Firefox:
[webhint-1.2.1.zip](https://github.com/webhintio/hint/files/3871934/webhint-1.2.1.zip)
=> Fix: Severity icon color

packages/hint/docs/user-guide/development-flow-integration/circleci.md, packages/hint/docs/user-guide/development-flow-integration/travis-and-azure.md, packages/hint/docs/user-guide/development-flow-integration/travisci.md, packages/hint/docs/user-guide/telemetry/summary.md, packages/hint/src/bin/hint.ts, packages/hint/src/lib/cli/analyze.ts, packages/hint/src/lib/cli/options.ts, packages/hint/src/lib/types.ts
=> Breaking: Use `telemetry` instead of `tracking`

packages/connector-local/src/connector.ts, packages/connector-local/tests/tests.ts
=> Fix: Check in connector local that the target is a file

packages/extension-browser/src/devtools/views/app.fluent.css, packages/extension-browser/src/devtools/views/app.photon.css
Fix #3365
Make sure you:
This is how it looks now:
=> Fix: Color contrast with errors

packages/hint/docs/user-guide/index.md, packages/hint/src/lib/cli/analyze.ts
=> Chore: Change configurations message

packages/extension-vscode/README.md, packages/extension-vscode/package.json
=> Docs: Improve VS Code readme and take it out of preview

packages/connector-local/src/connector.ts, packages/utils-network/src/as-uri.ts
=> Fix: Support for files with spaces in its names

packages/connector-puppeteer/src/connector.ts
=> Fix: Allow ignore HTTP Methods

packages/formatter-html/src/assets/styles/scan/scan-results.css
=> Fix: Close/Expand all button

packages/utils/src/content-type.ts, packages/utils/tests/content-type.ts
=> Fix: Media type for php files

packages/formatter-html/src/views/pages/report.ejs
Make sure you:
this prevent a webhint error on the report page :-)
=> add initial-scale=1 to meta viewport tag

packages/connector-jsdom/src/connector.ts, packages/connector-local/src/connector.ts, packages/formatter-excel/src/formatter.ts, packages/hint-html-checker/src/hint.ts, packages/hint-http-compression/src/hint.ts, packages/hint-http-compression/tests/_tests.ts, packages/hint-http-compression/tests/tests-http.ts, packages/hint-http-compression/tests/tests-https.ts, packages/hint-no-friendly-error-pages/src/hint.ts, packages/hint-sri/src/hint.ts, packages/hint-ssllabs/src/hint.ts, packages/hint-strict-transport-security/src/hint.ts, packages/hint-strict-transport-security/tests/http-tests.ts, packages/hint-strict-transport-security/tests/https-tests.ts, packages/utils-connector-tools/src/requester.ts, packages/utils-create-server/src/same-thread-server.ts, packages/utils-json/src/schema-validator.ts, packages/utils-network/src/request-json-async.ts, release/lib/git-helpers.ts, release/lib/utils.ts
=> Chore: Use object spread syntax over Object.assign

packages/hint/docs/user-guide/server-configurations/apache.md
Make sure you:
Removed incorrect backtick in apache snippet.
=> Docs: remove incorrect backtick

packages/parser-manifest/src/schema.json, packages/parser-manifest/src/types.ts
=> Fix: Added maskable to icon.purpose in manifest

packages/extension-browser/src/images/icon-severity-warning.svg
=> Fix: Icon label for warning in Firefox extension

packages/hint-sri/src/hint.ts
=> Fix: Remove unnecessary Promise.resolve in hint-sri

packages/connector-puppeteer/src/connector.ts, packages/extension-browser/tests/webhint.ts
=> Chore: Allow running tests with only puppeteer installed

packages/hint-validate-set-cookie-header/src/hint.ts, packages/hint-validate-set-cookie-header/tests/tests.ts
Make sure you:
Report all cookie errors instead of exiting early when a category reports errors.
Fixes #2642
=> Fix: Report all cookie errors

packages/hint/docs/about/FAQ.md
=> Docs: Update FAQ for browsers, editors, and online scanner

README.md, packages/hint/docs/about/GOVERNANCE-draft.md, packages/hint/docs/about/PROJECT_CHARTER-draft.md, packages/hint/docs/about/PROJECT_CHARTER.md
This is part of the work requested by the OpenJS Foundation in #3163 and needs approval from the maintainers and maybe OpenJS' CoC
=> Docs: Charter and Governance

packages/hint-button-type/src/hint.ts, packages/utils-dom/README.md, packages/utils-dom/package.json, packages/utils-dom/src/characterdata.ts, packages/utils-dom/src/comment.ts, packages/utils-dom/src/create-element.ts, packages/utils-dom/src/cssstyledeclaration.ts, packages/utils-dom/src/documenttype.ts, packages/utils-dom/src/elements/htmlanchorelement.ts, packages/utils-dom/src/elements/htmlbodyelement.ts, packages/utils-dom/src/elements/htmlhtmlelement.ts, packages/utils-dom/src/find-original-element.ts, packages/utils-dom/src/globals.ts, packages/utils-dom/src/htmldocument.ts, packages/utils-dom/src/htmlelement.ts, packages/utils-dom/src/index.ts, packages/utils-dom/src/node.ts, packages/utils-dom/src/text.ts, packages/utils-dom/src/types.ts, packages/utils-dom/tests/axe.ts, packages/utils-dom/tests/elements/htmlanchorelement.ts, packages/utils-dom/tests/globals.ts, packages/utils-dom/tests/html.ts, packages/utils-dom/tests/htmldocument.ts, packages/utils-dom/tests/htmlelement.ts, packages/utils-dom/tests/node.ts
Make sure you:
Add and update APIs to better align with DOM standards.
Updates aim to provide sufficient support to run axe-core.
=> Breaking: Update APIs to support axe-core

packages/hint/docs/contributor-guide/getting-started/development-environment.md
=> Docs: Update steps for first build

packages/hint-disown-opener/src/_locales/en/messages.json, packages/hint-disown-opener/src/hint.ts, packages/hint-disown-opener/tests/tests.ts
=> Fix: Remove HTML from messages

packages/utils-worker/src/connector.ts
Make sure you:
[util-worker]
Remove FetchEnd event queuing which was previously implemented to ensure the document element was ready (via a DOM snapshot). The document element is optional so this created an unnecessary delay especially for pages with large DOMs.
In the future we should introduce a mechanism to send an updated FetchEnd event when the DOM snapshot is ready.
Fixes #3771
=> Fix: Don't delay FetchEnd for DOM snapshot

.vscode/launch.json
=> Fix: Run AVA test configuration in launch.json

release/tasks/release.ts, release/tasks/validate-environment.ts
=> New: Add publishing scripts for OVSX

packages/utils-compat-data/scripts/mdn-browser-compat-data.js, packages/utils-compat-data/src/browsers.ts
Make sure you:
This commit add the property mdn_url for all the html elements.
Additionally, as a side effect, a bug was found in the generation
of this file, and now the file size is smaller.
Fix #3901
=> Fix: Generated file `browser-compat-api` incomplete

packages/hint-manifest-icons/package.json, packages/hint-manifest-icons/src/_locales/en/messages.json, packages/hint-manifest-icons/src/hint.ts, packages/hint-manifest-icons/tests/tests.ts, packages/parser-manifest/src/schema.json, packages/parser-manifest/src/types.ts
=> Fix: Icon purpose doesn't support combination of values

packages/hint/src/lib/hint-context.ts, packages/utils-tests-helpers/src/hint-runner.ts, packages/utils-tests-helpers/src/hint-test-type.ts, packages/utils-types/src/index.ts, packages/utils-types/src/problem-documentation.ts, packages/utils-types/src/problems.ts
=> New: Support documentation link and text in a report

packages/hint-compat-api/src/_locales/en/messages.json, packages/hint-compat-api/src/css.ts, packages/hint-compat-api/src/html.ts, packages/hint-compat-api/tests/css.ts, packages/hint-compat-api/tests/html.ts, packages/utils-compat-data/src/browsers.ts, packages/utils-compat-data/src/css.ts, packages/utils-compat-data/src/html.ts, packages/utils-compat-data/tests/browsers.ts
Make sure you:
This PR will allows to Webhint to report an specific url and text for `hint-compat-api`, so we can point to the user to the MDN website.
Fix #3769
=> Include links and text in problem reports for hint-compat-api

packages/hint-axe/src/_locales/en/messages.json, packages/hint-axe/src/util/axe.ts, packages/hint-axe/tests/color.ts, packages/hint-axe/tests/keyboard.ts, packages/hint-axe/tests/language.ts
=> New: Provide actual link to the package documentation in aXe

.vscode/launch.json
=> Fix: Ava tests debug

packages/hint/src/lib/cli/analyze.ts
=> Fix: Silent mode in CI

packages/hint-compat-api/docs/html.md, packages/hint-compat-api/src/html.ts, packages/hint-compat-api/tests/fixtures/html/ignore.html, packages/hint-compat-api/tests/html.ts
Make sure you:
As discussed in https://github.com/webhintio/hint/issues/3951
/cc @antross , @molant
=> Ignore `autocomplete` html element

packages/hint-validate-set-cookie-header/src/hint.ts
=> Fix: Cookie name reported in lower case

.github/workflows/3rdparty.yml, release/lib/utils.ts, release/main.ts, scripts/update-3rd-party.ts
Fix #3413
Make sure you:
This PR will create a Github action that will run every Saturday to update the 3rd party libraries data.
If tests pass, it will commit directly to master.
If tests fail, it will create a pull request so we can fix the issues and then manually merge it.
=> New: Action to update 3rd party data

.github/workflows/3rdparty.yml
=> Fix: Use GITHUB_TOKEN in 3rd party action

packages/formatter-html/src/_locales/en/messages.json, packages/formatter-html/src/assets/styles/scan/scan-results.css, packages/formatter-html/src/views/partials/scan-result-item.ejs
=> New: Show 3rd party documentation links on the HTML formatter

packages/extension-browser/src/_locales/en/messages.json, packages/extension-browser/src/devtools/views/controls/print-link.css, packages/extension-browser/src/devtools/views/controls/print-link.tsx, packages/extension-browser/src/devtools/views/pages/results/header.css, packages/extension-browser/src/devtools/views/pages/results/header.tsx
Make sure you:
Added scan result PDF generation in Browser Extension
-----------------------------------------------------------------------------------------------------------------------
Fix #3943
=> New: Added pdf printing from scan result (browser extension)

packages/formatter-html/src/views/partials/scan-result-category-item.ejs, packages/formatter-html/src/views/partials/scan-result-item.ejs, packages/formatter-html/src/views/partials/scan-result.ejs
=> Fix: Broken 3rd party logo in HTML Formatter

azure-pipelines/dependabot.yml
=> Fix: Run CI for dependency updates on Linux

packages/hint/docs/contributor-guide/getting-started/development-environment.md
Make sure you:
Fixes broken anchor link in docs for step 4.
=> [Docs] Fixes a broken anchor link in contributor documentation.

packages/configuration-development/index.json, packages/configuration-development/package.json, packages/configuration-web-recommended/index.json, packages/configuration-web-recommended/package.json, packages/extension-browser/package.json, packages/extension-browser/tsconfig.json, packages/hint-leading-dot-classlist/package.json, packages/utils-worker/package.json
Make sure you:
Enabled classList leading 'dot' warning hint
--------------
Fixes [#4046](https://github.com/webhintio/hint/pull/4046#pullrequestreview-508535732)
=> Chore: Enabled classList leading 'dot' warning hint

packages/hint-no-broken-links/src/hint.ts
Fix #2034
Make sure you:
In `no-broken-links` hint use `for..of` loop for collecting requests in `createReports` function which return "real" promises instead of unrelated `Promise.resolve()`.
=> Chore: Return real promises in no-broken-links#createReports

azure-pipelines/main.yml, azure-pipelines/performance.yml, azure-pipelines/vm-init-script.sh, packages/utils-worker/package.json, packages/utils-worker/src/shared/types.ts, packages/utils-worker/tests/helpers/runner.ts, packages/utils-worker/tests/helpers/types.ts, packages/utils-worker/tests/integration.ts, packages/utils-worker/tests/test-perf.ts
Make sure you:
This PR adds some initial perf tests and configures azure pipelines to run them on main branch.
=> New: Perf tests

packages/hint-http-compression/README.md, packages/hint-http-compression/src/hint.ts, packages/hint-http-compression/src/types.ts, packages/hint-http-compression/tests/_tests.ts, packages/hint-http-compression/tests/tests-http.ts
=> Fix: Change report severity for small files.

packages/create-hint/package.json, packages/create-hint/webpack.config.js, packages/create-hintrc/package.json, packages/create-hintrc/webpack.config.js
=> Fix: Update 'create' packages to webpack 5

packages/connector-local/README.md
=> Docs: Fix typo in `README.md`

README.md
=> Docs: Remove duplicate in README.md

yarn.lock
=> Upgrade: Bump prismjs from 1.22.0 to 1.23.0

packages/hint/docs/user-guide/configuring-webhint/summary.md
Fixes some broken Markdown in the docs.
=> Assorted fixes in "Configure webhint" docs

packages/hint-ssllabs/package.json, packages/hint-ssllabs/src/api.ts, packages/hint-ssllabs/src/hint.ts, packages/hint-ssllabs/src/types.ts, packages/hint-ssllabs/tests/tests.ts, yarn.lock
=> Fix: Resolve vulnerabilities

packages/extension-browser/package.json, packages/extension-browser/webpack.config.js, packages/extension-vscode/package.json, packages/utils-worker/package.json, packages/utils-worker/webpack.config.js, scripts/lint-dependencies.js, yarn.lock
=> Fix: Update vsce dependency

yarn.lock
=> Fix: Some other vulnerabilities

.github/workflows/3rdparty.yml
Make sure you:
Aligning schedule with dependabot.
=> Chore: Update 3rd party action schedule

packages/extension-browser/package.json, yarn.lock
=> Chore: Revert "Upgrade: Bump @types/chrome from 0.0.149 to 0.0.158"

packages/extension-vscode/src/utils/analyze.ts, packages/extension-vscode/src/utils/problems.ts, packages/extension-vscode/tests/utils/problems.ts
=> Fix: Squiggles in vscode insider

packages/hint-meta-viewport/README.md
=> Docs: Fix links about mdn viewport meta tag

README.md
=> chore: update links without -draft

packages/extension-browser/tests/background-script.ts
=> Fix: Build failing, updated test

packages/connector-jsdom/src/evaluate-resource-loader.ts, packages/connector-jsdom/src/resource-loader.ts
Make sure you:
Addressing the issues in the PR created by dependabot to upgrade jsdom to 12.2.14
=> Upgrade: Fix jsdom upgrade error

release/lib/utils.ts, release/tasks/get-packages.ts, release/tasks/release.ts, yarn.lock
Make sure you:
Fix errors when upgrading typescript to 4.5.5
=> Upgrade: Fix errors when upgrading typescript to 4.5.5

release/lib/git-helpers.ts, scripts/utils/exec.js
=> Chore: Fix release script

packages/utils-compat-data/package.json, yarn.lock
=> Upgrade: Bump @mdn/browser-compat-data from 4.1.6 to 4.1.10

package.json, packages/hint-no-vulnerable-javascript-libraries/src/snyk-snapshot.json, packages/parser-manifest/src/schema.json, packages/parser-manifest/src/schema.ts, packages/parser-typescript-config/src/schema.json
=> Update: Update 3rd party data

packages/hint/docs/contributor-guide/getting-started/development-environment.md
Make sure you:
Updates Step 3 to reflect the HTTPS as the recommended way for setting up development environment.
=> Docs: Update development-environment.md, step 3

packages/extension-browser/src/content-script/webhint.ts, packages/hint/src/lib/@types/browserslist.d.ts, packages/hint/src/lib/config.ts, packages/hint/tests/lib/config.ts, packages/utils-worker/src/webhint.ts
=> New: Exclude IE from default browsers

README.md, package.json, packages/create-hint/package.json, packages/create-hintrc/package.json, packages/create-parser/package.json, packages/extension-vscode/package.json, packages/hint/README.md, packages/hint/package.json, packages/parser-jsx/package.json, packages/parser-typescript/package.json
Make sure you:
Align specified minimum node version with that required by recent dependency updates.
=> Breaking: Raise min required node version to 14

packages/utils-compat-data/scripts/extra-data.js, packages/utils-compat-data/scripts/mdn-browser-compat-data.js, packages/utils-compat-data/src/css.ts, packages/utils-compat-data/src/matches.ts
Make sure you:
Migrate MDN `matches` data to webhint due to proposed removal.
Goal is to avoid regressions and to enable future extensions within the
webhint project if needed.
Fix #5126
=> Chore: Migrate 'matches' data from MDN

yarn.lock
Make sure you:
Updating yarn.lock indirect dependencies
=> Update: Updating yarn.lock indirect dependencies

packages/hint-no-protocol-relative-urls/src/hint.ts, packages/hint-no-protocol-relative-urls/tests/_generate-tests.ts, packages/hint/src/lib/hint-context.ts, packages/utils-tests-helpers/src/hint-runner.ts, packages/utils-tests-helpers/src/hint-test-type.ts, packages/utils-tests-helpers/tests/hint-runner-helpers.ts
=> [Feature]: Adding code fix for no-protocol-relative-urls hint + Adding test infra for code fixes

packages/extension-vscode/src/quickfix-provider.ts, packages/extension-vscode/src/server.ts, packages/extension-vscode/src/utils/webhint-utils.ts, packages/extension-vscode/tests/quickfix-provider.ts, packages/extension-vscode/tests/utils/webhint-utils.ts
Make sure you:
Also fix sorting of options when multiple reports occur at the
same location.
=> New: Add options to ignore axe-core rules

packages/hint-css-prefix-order/src/hint.ts, packages/hint-css-prefix-order/tests/fixtures/different-property-at-end.css, packages/hint-css-prefix-order/tests/fixtures/different-property-at-end.fixed.css, packages/hint-css-prefix-order/tests/fixtures/interleaved-prefixes.fixed.css, packages/hint-css-prefix-order/tests/fixtures/mixed-with-prefixes-last.fixed.css, packages/hint-css-prefix-order/tests/fixtures/prefixed-values-last.fixed.css, packages/hint-css-prefix-order/tests/fixtures/prefixes-last-same-line.fixed.css, packages/hint-css-prefix-order/tests/tests.ts
=> New: Add fix to correctly reorder prefixed properties

packages/extension-vscode/src/quickfix-provider.ts, packages/extension-vscode/src/server.ts, packages/extension-vscode/src/utils/problems.ts, packages/extension-vscode/tests/quickfix-provider.ts
Make sure you:
Creates a new "fix" `CodeAction` when `problem.fixes` exists that contains
both an `edit` to communicate the fix to VS Code and a `command` to allow
the language server host to detect when a fix has been applied.
=> New: Pass code fixes to VS Code

.github/CODEOWNERS
Make sure you:
Stops automatically adding @antross to PR reviews.
=> Chore: Remove @antross from CODEOWNERS

packages/hint-meta-charset-utf-8/src/hint.ts, packages/hint-meta-charset-utf-8/tests/tests.ts, packages/utils-dom/src/htmlelement.ts, packages/utils-dom/tests/htmlelement.ts
=> [Code Fixes]: Implementing Code fixes for hint-meta-charset-utf-8

packages/utils-connector-tools/src/requester.ts
Make sure you:
Updates the `user-agent` for the `requester` class.
------
Fix #5258
=> Fix: Updating the user-agent in the requester.

packages/hint-ssllabs/package.json, yarn.lock
Make sure you:
Updating got to  version 11.8.5
------
Fix #5260
=> Update: Updating got to 11.8.5

yarn.lock
Make sure you:
Updating the resolved version of canisue-lite to version "1.0.30001387". This was done through and automated script that was prompt by yarn.
=> Update: Updating browserslists version

package.json, yarn.lock
Make sure you:
Updates the thenify version to 3.3.1 to address a security update.
=> Update: Bumps thenify version

packages/hint-no-vulnerable-javascript-libraries/src/snyk-snapshot.json, packages/parser-typescript-config/src/schema.json
Make sure you:
Checking in 3rd party dependencies marked by update:3rd-party.
------
Close #5280, #5245, #5194
=> Update: Bumping 3rd party dependencies

packages/extension-browser/package.json, yarn.lock
Make sure you:
This patch updates the web-ext dependency to resolve a security issue reported by dependabot:
https://github.com/webhintio/hint/security/dependabot/47
=> Update web-ext dependency

.github/CODEOWNERS
Make sure you:
Updating owners.
=> Chore: Updating CODEOWNERS

packages/hint-no-protocol-relative-urls/README.md
Make sure you:
Remove IE 7/8 note (no longer relevant)
=> Docs: Remove IE 7/8 note (no longer relevant)

yarn.lock
Make sure you:
Upgrade: Bump vm2 from 3.9.11 to 3.9.17
=> Upgrade: Bump vm2 from 3.9.11 to 3.9.17

packages/parser-typescript-config/src/schema.json
Make sure you:
Adds `Bundler` as a valid `moduleResolution` strategy 
from [typescriptlang.org](https://www.typescriptlang.org/tsconfig#moduleResolution):
>'bundler' for use with bundlers. Like node16 and nodenext, this mode supports package.json "imports" and "exports", but unlike the Node.js resolution modes, bundler never requires file extensions on relative paths in imports.
resolves #5719
=> fix: Update moduleResolution options

packages/extension-browser/package.json, packages/utils-worker/package.json
Make sure you:
Increase the size-limit after taking some updates.
=> Chore: Increasing size limit for package files in browser extension

packages/create-hintrc/package.json, packages/hint/package.json, packages/utils-worker/package.json, packages/utils-worker/tests/integration.ts, yarn.lock
Make sure you:
Bringing `Browserlist` to version `4.23.0` and `caniuse-lite` to version `1.0.30001614`
=> Update: Browserlist and caniuse to latest versions

yarn.lock
Make sure you:
Upgrade: Bump caniuselite to 1.0.30001653
=> Upgrade: Bump caniuselite to 1.0.30001653

packages/hint-image-optimization-cloudinary/package.json, yarn.lock
Make sure you:
Upgrade: Bump Cloudinary to version 2.2.0
=> Upgrade: Bump Cloudinary to version 2.2.0
