webhintio/hint

docs/about/CONTRIBUTORS.md
Resolves issue #279 
Using https://github.com/kentcdodds/all-contributors to clean up the Contributors page
Have to manually remove the links to user/project commit history that gets generated with the icon. Looking over the readme.md for all-contributors, I can't tell if there's a way to just use the icon and not add a link. 
Also people may want to edit their contribution categories at some point.
=> Contributors page update

tests/lib/collectors/utils/requester.ts
This test is failing because of the hardcoded port.
=> Fix failing request test using hardcoded port.

package.json
With this field npm will show a warning and Yarn will prevent the installation if the package is installed with an unsupported node version.
=> Specify required node version in package.json

docs/user-guide/rules/meta-charset-utf-8.md
`recomanded` -> `recommended`
https://sonarwhal.com/docs/user-guide/rules/meta-charset-utf-8.html
=> Fix typo in meta-charset-utf-8.md

docs/about/CONTRIBUTORS.md
@molant I've got other changes coming to the CSS. @qzhou1607 Is there anyway to get the contributors table element wrapped in a div with `class="section contributors"`?
=> Contributors style

src/lib/cli.ts
Repro:
1) At the command line, run “sonar www.example.com”
2) Observe the first line of output
Expected: “Analyzing…”
Actual: “Analyzing…”
=> Fix typo in cli scan::start output (Analizing)

docs/user-guide/rules/no-friendly-error-pages.md
There is a missing *not* in the 403 page example
=> Typo in example page

docs/user-guide/index.md, src/lib/sonar.ts, src/lib/types.ts, src/lib/utils/normalize-rules.ts, tests/lib/sonar.ts, tests/lib/utils/normalize-rules.ts
**Do not merge** until the issue with the build not working on UNIX systems is fixed. The tests were passing, but I've made a few more changes without running the tests (since I can't right now). The Travis tests will obviously fail because the build is not passing at the moment. I just wanted to get any feedback from @molant before he leaves on vacation.
This change allows arrays to be passed for `rules` in the config:
```
{
"rules": [
"rule1",        // Default to "error"
"rule2:warn",   // Switch to warn
"rule3:off",    // Quickly disable a rule
["rule4", {
something: true
}]
]
}
```
It also allows for `warn` and `off` shorthands:
```
{
"rules": [
"rule1",          // Default to "error"
"?rule2",        // Switch to warn
"-rule3"        // Quickly disable a rule
}
```
My change is …
=> 283 - Improve rules configuration. Allow rules to be an array.

src/lib/utils/location-helpers.ts, tests/lib/rules/disown-opener/tests.ts
Escape character `'` in selectors in location-helpers.ts
Fix #404
=> Fix: SyntaxError when using jsdom

src/lib/sonar.ts, tests/helpers/connectors.ts, tests/helpers/test-server.ts, tsconfig.json
=> Build: Generate files `d.ts`

.sonarrc, docs/user-guide/rules/index.md, docs/user-guide/rules/validate-set-cookie-header.md, package-lock.json, src/lib/rules/validate-set-cookie-header/validate-set-cookie-header.ts, src/lib/types/rules.ts, tests/helpers/rule-runner.ts, tests/lib/rules/validate-set-cookie-header/tests.ts
Fix #24 
Note: It's possible for one response to contain multiple `Set-Cookie` headers. The `cdp` connector concatenate all `Set-Cookie` headers into one single string (no delimiter to split it into an array). And `jsdom` returns an array containing all the `Set-Cookie` headers. So analyzing the `Set-Cookie` headers one by one seems impossible using the `cdp` connector.
The first commit is cherry picked from #370. So only commit 2 needs to be reviewed in this PR.
=> New: Add rule to check `Set-Cookie` header

src/lib/connectors/shared/remote-debugging-connector.ts, tests/lib/connectors/invalid-url.ts
Initial work. I'd like to add some tests to this but having some quiet time is a challenge at the moment.
=> Fix #389 Cannot read property 'response' of undefined when accessing inexistant url

package-lock.json, package.json, src/lib/cli.ts, src/lib/cli/browserslist-generator.ts, src/lib/cli/sonarrc-generator.ts, tests/lib/cli/browserlist-generator.ts, tests/lib/cli/sonarrc-generator.ts
Fix #446 
I'm currently working on adding tests, but feedback on the options are welcome:
I checked out a few dependents of `browserslist` to see what queries are most often used. `last 2 versions` show up frequently, but a lot of them simply provide an interface to pass their users' queries to `browserslist`, which means they use `browserslist`'s default if not defined. Here in this PR, we have 4 options in the beginning:
* Default list from browserslist
* Last 2 versions of all browsers
* Add by percentage of usage statistics. (e.g., `>= 5%`, 5% by default)
* Add by specific browser type and version number range. (e.g., `IE 6-8`)
The users can define the value of `usage percentage`, `browser type` and the `version numbers`. Also the dialogue will be prompted in a recursive manner so if …
=> New: Ask about browserslist when generating config

docs/user-guide/rules/html-checker.md, src/lib/rules/html-checker/html-checker.ts, tests/lib/rules/html-checker/tests.ts
Fix #474
366 errors/warnings from `html-checker` are reduced to ~ 20:
=> Chore: Use compact html checker reports

src/lib/rule-context.ts
Fix #478
The page loads some scripts multiple times, which results in the duplicate messages. It makes sense but looks like duplicate evaluation, should we add a filter similar to what we did to `jsdom`  in https://github.com/sonarwhal/sonar/pull/468?
=> Fix: Remove `null` locations in the error message

src/lib/connectors/jsdom/jsdom.ts, src/lib/connectors/shared/remote-debugging-connector.ts
Fix #469
The reason that this issue happened is as below:
The page has many failed requests to https://betterment.report-uri.io/r/default/csp/reportOnly. Both `onResponseReceived` and `onLoadingFailed` were fired upon the failed requests. In the beginning, this request exists in `this._requests`, so  the check below in `onLoadingFailed` passes. But soon after this check the request is removed from `this._requests` in the `onResponseReceived` since it is running cocurrently. So later on in `onLoadingFailed`, the destructuring `const { request: { url: resource } } = this._requests.get(params.requestId)` fails, because at this stage, the request has already been removed from `this._requests` and `this._requests.get(params.requestId)` returns nothing.
The check in `onLoadingFailed` that gets …
=> Fix: Fix error in `onLoadingFailed`

package.json, src/lib/rules/html-checker/html-checker.ts, tests/helpers/test-server.ts, tests/lib/rules/html-checker/tests.ts, tests/lib/rules/strict-transport-security/tests.ts
* Remove `concurrency` from `package.json` and let `ava` decide how
many should be run depending on the CPU
* Pick random port for `test-server` so it doesn't have to look for an
available one as many times as before
* Fix issue with `static-transport-protocol` where the response could
be empty and thus producing an exception
* Change test server for `html-checker` and how the html text is
accessed
Fix #502
=> Fix: Make tests more reliable and faster

package.json, src/lib/cli/analyze.ts, tests/lib/cli/analyze.ts
=> Fix: Generate correctly `.sonarrc` if not found

src/bin/sonar.ts
`#!/usr/bin/env node` was causing sonar to throw `env: node\r: No such file or directory` from the command line on my Mac.
Ref https://github.com/sonarwhal/sonar/issues/564
Fix #564
Close #564
Make sure you:
=> Fix: Removing shebangs from top of sonar.js

package.json, tsconfig.json
Make sure you:
From https://www.typescriptlang.org/docs/handbook/compiler-options.html:
> --newLine: Use the specified end of line sequence to be used when emitting files: 'crlf' (windows) or 'lf' (unix). "
Fix #564 
@molant Please test this, and confirm it works! Thanks!
=> Build: Make TypeScript enforce `LF` newlines

src/lib/rules/content-type/content-type.ts
⚠️ This depends on https://github.com/jshttp/mime-db/pull/90.
See also: https://github.com/jshttp/mime-db/issues/77.
=> Chore: Remove the overwrite from `content-type` rule

.travis.yml, appveyor.yml
Make sure you:
[`canvas-prebuilt` doesn't have a binary for node 9 yet](https://github.com/node-gfx/node-canvas-prebuilt/issues/26) so we have to lock CI to the latest LTS.
=> Chore: Lock node version to 8.x in CI

src/lib/rules/manifest-app-name/manifest-app-name.ts, tests/lib/rules/manifest-app-name/tests.ts
Report an error if the manifest content type is not valid.
----------------------
Fix #610
Make sure you:
=> Fix: Rule manifest-app-name

docs/user-guide/connectors/index.md, src/bin/sonar.ts, src/lib/connectors/utils/requester.ts
Make sure you:
Change the timeout from 30 seconds to 10 when using `requester`
Fix #585
=> Fix: Reduce `timeout` for requests

.github/CONTRIBUTING.md
Make sure you:
(Hi, this is the tiniest first PR possible, but hopefully I can make bigger contributions in future!)
Add a trailing "/" to the Pull Request Guidelines link. Without it, it redirects me [here](https://sonarwhal.com/dist/docs/contributor-guide/contributing/pull-requests/), which gives a 404.
=> Docs: Fix PR Guidelines link in CONTRIBUTING.md

src/lib/connectors/debugging-protocol-common/debugging-protocol-connector.ts, src/lib/connectors/jsdom/jsdom.ts, src/lib/types/events.ts
Make sure you:
The origin (element) of the `traverse::up` and `traverse::down` events is needed for some JSLL rules. It was included as part of this PR https://github.com/sonarwhal/sonarwhal/pull/690. But since we are moving all the JSLL rules to external rules, this change needs to be merged separately.
=> New: Add `element` info to `traverse` events

src/lib/utils/content-type.ts
Make sure you:
From https://tools.ietf.org/html/rfc3023#page-5:
> If an XML document -- that is, the unprocessed, source XML document -- is readable by casual users, text/xml is preferable to application/xml.
=> Breaking: Use `text/xml` as the media type for XML

packages/sonarwhal/src/lib/utils/misc.ts, packages/sonarwhal/src/lib/utils/resource-loader.ts, packages/sonarwhal/tests/lib/utils/resource-loader.ts
Make sure you:
* Change the path to load external rules back to `process.cwd()`.
* Add additional check to verify the name of the resource loaded.
=> Fix: Validate resource name on load

packages/sonarwhal/src/lib/cli/analyze.ts, packages/sonarwhal/src/lib/config.ts, packages/sonarwhal/tests/lib/cli/analyze.ts, packages/sonarwhal/tests/lib/config.ts
Make sure you:
In the current code, if a rule has not been installed, when user scans a site, an error is thrown and the user will be asked to re-generate a valid `.sonarwhalrc` even though there already is one. The correct behavior should be prompt to ask the user if they want to install the missing rules first. So this PR moves the validation of rule configurations after the rules have been installed.
=> Fix: Install rules before validate

packages/sonarwhal/src/lib/utils/rule-helpers.ts, packages/sonarwhal/tests/lib/utils/rule-helpers.ts
Make sure you:
Allow package names to be added to the ruleIds in tests, otherwise the rules can't get loaded correctly.
=> Fix: Allow packageName to be added in tests

packages/sonarwhal/src/lib/cli/rules/new-rule.ts, packages/sonarwhal/src/lib/cli/rules/templates/new-rule/.sonarwhalrc.hbs
=> Fix: Fix .sonarwhalrc generated with `--new-rule`

.yarnrc
Make sure you:
Yarn's workspaces feature is now (and has been for quite some time) enabled by default.
From https://yarnpkg.com/lang/en/docs/workspaces/#toc--tricks:
> Workspaces are stable enough to be used in large-scale applications
and shouldn’t change anything to the way the regular installs work,
but if you think they’re breaking something, you can disable them
by adding the following line into your Yarnrc file
>
>   `workspaces-experimental false` 
See also: https://github.com/yarnpkg/yarn/commit/d39a2e85c13ff61f5785e071ac73aed1aa037640
=> Chore: Remove `.yarnrc` file

README.md, packages/sonarwhal/src/lib/cli/options.ts, packages/sonarwhal/src/lib/config.ts, packages/sonarwhal/src/lib/types.ts, packages/sonarwhal/tests/lib/config.ts
This change will allow users to explicitly pass the formatters via cmd line.
--------------------------------------------------------------------
Fix #888
Make sure you:
=> New: Support for user to set the formatter via cli

packages/sonarwhal/src/lib/utils/resource-loader.ts, packages/sonarwhal/tests/lib/utils/resource-loader.ts
This commit shows an error message when a resource fails
loading a dependency.
Fix #1043
Make sure you:
=> Chore: Show message when binary fails to load

packages/hint-no-broken-links/src/hint.ts, packages/hint-no-broken-links/tests/tests.ts
Make sure you:
I discovered a bug in the "no-broken-links" hint, which causes it to ignore a base tag with an href value when resolving relative URLs.
I put together a fix which works when testing it with a site hosted on GitHub pages. However I was not able to add any tests as I couldn't get the tests to work in the first place. I followed the guide on the website. (https://webhint.io/docs/contributor-guide/getting-started/development-environment/)
Are the tests currently broken or am I doing something wrong?
=> Fix: Handle base[href] tags

packages/formatter-html/src/views/partials/scan-error-message.ejs, packages/formatter-html/src/views/partials/scan-result.ejs
=> Fix: Hide report in HTML Formatter when the status is `error`

packages/hint/docs/user-guide/index.md, packages/hint/docs/user-guide/troubleshoot/summary.md
=> Docs: Add Troubleshoot section

packages/hint-no-broken-links/README.md, packages/hint-no-broken-links/src/hint.ts, packages/hint-no-broken-links/tests/tests.ts
Make sure you:
This pull request ensures that status codes are ignored when checking an URL of a [dns-prefetch](https://www.w3.org/TR/resource-hints/#dfn-dns-prefetch) or [preconnect](https://www.w3.org/TR/resource-hints/#dfn-preconnect) link. The spec for [Resource Hints](https://www.w3.org/TR/resource-hints) says that those type of links should only be used for DNS lookups, TCP handshakes, and optional TLS negotiations. Therefore I think checking the resource but ignoring the status code it returns is a good approximation to check those links.
I used https://example.com/404 in the tests to simulate a 404 response. But dns-prefetch and preconnect links should normally be used without any path in the URL. Is there a way to mock a server …
=> Fix: Ignore status codes for dns-prefetch and preconnect links

packages/connector-local/tests/tests.ts, packages/create-hint/tests/create-hint.ts, packages/create-hintrc/tests/create-hintrc.ts, packages/create-parser/tests/new-parser.ts, packages/extension-vscode/tests/fixtures/mocks.ts, packages/hint-typescript-config/tests/import-helpers.ts, packages/hint/package.json, packages/hint/tests/lib/cli.ts, packages/hint/tests/lib/cli/analyze.ts, packages/hint/tests/lib/config.ts, packages/hint/tests/lib/types/parser.ts, packages/hint/tests/lib/utils/appinsights.ts, packages/hint/tests/lib/utils/npm.ts, packages/parser-css/tests/basic-tests.ts, packages/parser-css/tests/interface-tests.ts, packages/parser-javascript/tests/tests.ts, packages/parser-webpack-config/tests/webpack-config.ts, yarn.lock
Fix #1517
@antross I need your help hehehe.
As you can see, there is a lot of `as any`, e.g.:
`t.true((t.context.notifier.notify as any).calledOnce);`
In this case, I have defined `notifier.notify` as `() => any`, so calledOnce doesn't exists.
I think I have to use the type: `SinonSpy`:
```ts
interface SinonSpy<TArgs extends any[] = any[], TReturnValue = any>
extends Pick<
SinonSpyCallApi<TArgs, TReturnValue>,
Exclude<keyof SinonSpyCallApi<TArgs, TReturnValue>, 'args'>
>
```
But if I do something like:
```ts
type StubbedNotifier = {
notify: sinon.SinonSpy<any>;
update: {} | null;
};
```
and then I do:
```ts
const stubbedNotifier: StubbedNotifier = {
notify() { },
update: {}
};
```
I get the error:
`Type '() => void' is not assignable to type 'SinonSpy<any,any>'`
I think I'm missing …
=> Fix: Add types to tests

packages/hint-axe/README.md
Likely regressed during the rename to webhint.
=> Docs: Use "rules" not "hints" in aXe configuration

.idea/typescript-compiler.xml, packages/formatter-html/src/formatter.ts
Previously the HTML Formatter package output the HTML file with the filename `<url-analyzed>`. If you have query strings in your URL this will create a filename with a `?` symbol which is incompatible with some systems.
This update changes the saved filename to replace `?` with `-query-` so the URL is still readable but can be saved as the filename is no longer malformed.
=> Fix: Savename of HTMLformatter output replaces q-marks with -query-

packages/hint/src/lib/config.ts, packages/hint/src/lib/utils/logging.ts, packages/hint/tests/lib/utils/logging.ts
Make sure you:
Both `fromFilePath` and `loadBrowsersList` are no longer used by
the online scanner, CLI, or extensions. Deprecating prior to removal
since these APIs are public.
=> Chore: Deprecate unused `Configuration` methods

packages/extension-vscode/package.json
Make sure you:
Was previously incorrectly listed in `dependencies`.
=> Chore: Move `vscode` to `devDependencies`

packages/parser-manifest/src/parser.ts, packages/utils-debugging-protocol-common/src/debugging-protocol-connector.ts
It seems like with some chrome versions, the manifest parser runs twice, one when we are traversing the dom and the connector find the `link` element (`element::link`) and a second time when the connector loads the manifest. This second case seems to be the one that didn't happen before but now it is happening.
Make sure you:
=> Fix: Manifest parser runs twice

packages/extension-browser/src/content-script/webhint.ts, packages/extension-browser/src/devtools/panel/panel.css, packages/extension-browser/src/devtools/panel/views/pages/analyze.ts, packages/extension-browser/src/devtools/panel/views/pages/configuration.css, packages/extension-browser/src/devtools/panel/views/pages/configuration.html.ts, packages/extension-browser/src/devtools/panel/views/pages/configuration.ts, packages/extension-browser/src/devtools/panel/views/pages/results.ts, packages/extension-browser/src/devtools/panel/views/partials/category.css, packages/extension-browser/src/devtools/panel/views/partials/header.css, packages/extension-browser/src/devtools/panel/views/partials/header.ts, packages/extension-browser/src/devtools/panel/views/partials/page.css, packages/extension-browser/tests/content-script.ts
Make sure you:
Fix #1666
Prevent form submission when analysis is run with an invalid
`browserslist` query. Similarly, prevent form submission
when an invalid `RegExp` is provided for ignored URLs.
Update the analysis script gracefully handle invalid should
any be successfully submitted by falling back to defaults.
Also provide feedback to the user during query construction on
whether or not the query is valid and why.
=> Fix: Gracefully handle invalid browserslist and URL queries

package.json, scripts/check-commit-message.js, scripts/release.ts
=> Build: Use ' instead of ` in commit messages`

packages/hint-compat-api/src/core/api-hint.ts, packages/hint-compat-api/src/helpers/compat-base.ts, packages/hint-compat-api/src/helpers/compat-css.ts, packages/hint-compat-api/src/helpers/compat-html.ts, packages/hint-compat-api/src/types.ts, packages/hint-compat-api/tests/css-next.ts, packages/hint-compat-api/tests/css.ts, packages/hint-compat-api/tests/fixtures/css/appearance-disordered-prefixes.css, packages/hint-compat-api/tests/fixtures/css/appearance-only-prefixes.css, packages/hint-compat-api/tests/fixtures/css/appearance-splitted.css, packages/hint-compat-api/tests/fixtures/css/box-flex-prefixes.css
=> Ignore vendor prefixes reports when a property is not supported

packages/hint-sri/src/meta.ts
Make sure you:
I'm sorry for the confusion, but unfortunately my other pull request (#1690) did not fix the issue completely.
This pull request replaces the `oneOf` keyword with the `enum` keyword in the definition of the JSON schema. And this time I actually tested the changes by running the compiled changes with the `hint` command.
I think `oneOf` is meant for allowing different types, whereas `enum` is a special case where the type is always the same but can have different values.
https://json-schema.org/understanding-json-schema/reference/combining.html#oneof
https://json-schema.org/understanding-json-schema/reference/object.html#properties
=> Fix: Use enum instead of oneOf

packages/hint-performance-budget/src/meta.ts
Make sure you:
This pull request does just simplify the JSON schema of the `performance-budget` hint as discussed here: #1695.
It should not change any functionality.
=> Fix: Use only enum instead of oneOf in schema

azure-pipelines/all-versions.yml, azure-pipelines/latest-version.yml
Make sure you:
Increase the timeout to stop an agent to 90 minutes from the 60 default ones. The reason is that full test times are over 60 minutes in some of the platforms.
=> Build: Increase build timeout

packages/extension-browser/src/background-script.ts
Make sure you:
When undocked `sender.tab` exists and `sender.tab.id`
is `-1`. Preferring `message.tabId` fixes the issue.
Bundle for testing:
* [extension-browser-pr-1788.zip](https://github.com/webhintio/hint/files/2805444/extension-browser-pr-1788.zip)
=> Fix: Analyze when devtools is undocked

packages/hint-http-cache/src/hint.ts, packages/hint-http-cache/tests/tests.ts
Make sure you:
Split the error message reported when a static resource is not cached
long enough or it does not use the `immutable` directive into two to
make it clearer what the cause of the failure is.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Fix #1074
=> Breaking: Split error messages

packages/hint/src/lib/utils/location-helpers.ts, packages/hint/tests/lib/utils/fixtures/test-page.html, packages/hint/tests/lib/utils/location-helpers.ts
Make sure you:
Fix #1792
Also gracefully handle invalid selectors when generating locations.
=> Fix: Handle newlines in attribute values

packages/extension-browser/package.json, packages/extension-browser/src/@types/raw-loader.d.ts, packages/extension-browser/src/background-script.ts, packages/extension-browser/src/content-script/webhint.ts, packages/extension-browser/src/devtools/panel/panel.ts, packages/extension-browser/src/shared/types.ts, packages/extension-browser/tests/background-script.ts, packages/extension-browser/tests/content-script.ts, packages/extension-browser/tests/end-to-end.ts, packages/extension-browser/webpack.config.js, yarn.lock
Make sure you:
Refactor injection of the content-script from the background script to the panel, giving the panel control over what code injected; this also reduces the number of files included in the bundle and loaded by the extension.
As part of this change the build is now done in two passes; first to create the content-script bundle, then to create the extension bundle which raw-loads the content-script bundle.
Bundle for testing:
* [extension-browser-pr-1801.zip](https://github.com/webhintio/hint/files/2814725/extension-browser-pr-1801.zip)
Co-authored-by: Tony Ross <antross@gmail.com>
=> Chore: Panel injects content-script

packages/hint-x-content-type-options/README.md, packages/hint-x-content-type-options/src/hint.ts, packages/hint-x-content-type-options/tests/tests.ts, packages/hint/docs/user-guide/server-configurations/apache.md, packages/hint/docs/user-guide/server-configurations/iis.md
This reverts changes added to check for this header only
on scripts and stylesheets, and instead, checks for the header
on all resources. MDN suggests the former, but Chromium uses
this response header on more than script/stylesheets for
CORB.
Ref https://github.com/webhintio/hint/issues/1221
Close #1221
Make sure you:
=> Breaking: Update hint to check for XCTO header on all resources

packages/hint-typescript-config/src/target.ts, packages/hint-typescript-config/tests/target.ts
Make sure you:
Fix #1852
Drop the use of the `ScriptTarget` enum to avoid
needing any parts of the `typescript` package at
runtime. Use of this enum is not necessary as
we are maintaining a separate map regardless.
=> Fix: Remove runtime `typescript` dependency

packages/hint/docs/user-guide/concepts/formatters.md, packages/hint/src/lib/config.ts, packages/hint/src/lib/config/config-schema.json, packages/hint/tests/lib/config/config-validator.ts
=> Fix: Force `formatters` to be an `Array` only

packages/hint/src/bin/hint.ts, packages/hint/src/lib/utils/debug.ts
Make sure you:
Debug output was being printed when the environment variable `DEBUG`
was set, even if `--debug` parameter was not used.
Fix #1349
=> Fix: Honor `--debug` parameter even when `DEBUG` env is set

packages/formatter-html/src/assets/styles/scan/scan-results.css
Make sure you:
Fixes issue 588 in the webhint.io repo. This only fixes the print styles issue with the category hint summary covering the scan results across multiple pages. Other items that were mentioned in that issue were created into new issues. 
I also adjusted some styles so that things look a little bit better while printing and the "why is this important" and "how to fix this" button stay in place and don't randomly overlap other information on the page.
Here's a PDF printed from the page with updated styles/adjustments.
[Page Title-4.pdf](https://github.com/webhintio/hint/files/2882441/Page.Title-4.pdf)
=> Fix: HTML Formatter Print Styles

packages/parser-css/README.md, packages/parser-css/src/parser.ts, packages/parser-css/src/types.ts, packages/parser-css/tests/helpers/mocks.ts, packages/parser-css/tests/interface-tests.ts, packages/parser-javascript/README.md, packages/parser-javascript/src/parser.ts, packages/parser-javascript/src/types.ts, packages/parser-javascript/tests/tests.ts
Make sure you:
Allows hints for CSS and JavaScript source to correctly offset the
location of reported issues nested inside an HTML document.
=> New: Include element reference if source was inline in HTML

packages/hint-css-prefix-order/src/hint.ts, packages/hint-css-prefix-order/tests/tests.ts
Make sure you:
Locations reported by `postcss` are one-based wheraes those used within
`webhint` are zero-based. The hint-compat-api already accounted for
this discrepency and now hint-css-prefix-order does as well.
=> Fix: Off-by-one error with hint-css-prefix-order

packages/formatter-html/src/assets/styles/scan/scan-results.css, packages/formatter-html/src/views/partials/scan-result.ejs
Make sure you:
Fix #1985 and a misc accessibility bug. 
This PR fixes the expand all, close all button being cut off. Also removes an unnecessary` role="main" `on the results container. There is already a `<main>` element being used so the use of `role="main"` on a different container is of no value. Ran an accessibility checker that flagged this.
=> Fix button cutoff and misc a11y issue

packages/connector-chrome/tests/collect.ts, packages/connector-chrome/tests/evaluate.ts, packages/connector-chrome/tests/events.ts, packages/connector-chrome/tests/fetch-content.ts, packages/connector-chrome/tests/invalid-url.ts, packages/connector-chrome/tests/request-response.ts, packages/connector-jsdom/package.json, packages/connector-jsdom/src/connector.ts, packages/connector-jsdom/tests/collect.ts, packages/connector-jsdom/tests/evaluate.ts, packages/connector-jsdom/tests/events.ts, packages/connector-jsdom/tests/fetch-content.ts, packages/connector-jsdom/tests/invalid-url.ts, packages/connector-jsdom/tests/request-response.ts, packages/connector-jsdom/tsconfig.json, packages/connector-local/src/connector.ts, packages/extension-browser/package.json, packages/extension-browser/src/content-script/connector.ts, packages/extension-browser/src/content-script/webhint.ts, packages/extension-browser/tsconfig.json, packages/hint/src/lib/hint-context.ts, packages/hint/src/lib/types/html.ts, packages/hint/src/lib/utils/dom/create-html-document.ts, packages/hint/src/lib/utils/dom/find-original-element.ts, packages/hint/tests/lib/types/html.ts, packages/hint/tests/lib/utils/dom/find-original-element.ts, packages/utils-debugging-protocol-common/package.json, packages/utils-debugging-protocol-common/src/debugging-protocol-connector.ts, packages/utils-debugging-protocol-common/tsconfig.json
Make sure you:
Ref #1956 
Also fix some cases where use of the snapshot vs. original document were
inconsistent between connectors (except connector-local which needs to
be different).
Notable changes:
* All connectors now use `parser-html` to obtain an original source document
* Should we consider making `parser-html` fully built-in since HTML handling is so special?
* Snapshots are created with a reference to the original source document for locations
* This means we no longer use locations from the snapshot itself (I turned off locations for snapshots to ensure this)
* A new `findOriginalElement` helper was added to take an element from the snapshot and build a selector (plus filter function) …
=> Fix: Tie more elements from DOM snapshot back to original source

packages/formatter-html/src/assets/js/scan/scanner-common.js, packages/formatter-html/src/views/partials/scan-category-summary.ejs
Fix #2053
This commit also fix an issue when you refresh the
website after a category was clicked.
Make sure you:
=> Fix: Accessibility issue in mobile menu.

packages/hint-compat-api/tests/html-next.ts, packages/hint-compat-api/tests/html.ts, packages/hint-css-prefix-order/src/hint.ts, packages/hint-css-prefix-order/tests/fixtures/prefixes-last-same-line.html, packages/hint-css-prefix-order/tests/fixtures/prefixes-last-webkit.html, packages/hint-css-prefix-order/tests/tests.ts, packages/hint-disown-opener/src/hint.ts, packages/hint-meta-charset-utf-8/src/hint.ts, packages/hint-no-protocol-relative-urls/src/hint.ts, packages/hint-no-protocol-relative-urls/tests/tests.ts, packages/hint-sri/tests/tests-local.ts, packages/hint/docs/contributor-guide/guides/create-custom-hint.md, packages/hint/docs/contributor-guide/how-to/hint.md, packages/hint/src/lib/engine.ts, packages/hint/src/lib/hint-context.ts, packages/hint/src/lib/types/html.ts, packages/hint/src/lib/utils/dom/find-original-element.ts, packages/hint/tests/lib/engine.ts, packages/hint/tests/lib/types/html.ts, packages/hint/tests/lib/utils/dom/find-original-element.ts, packages/parser-css/src/parser.ts, packages/parser-css/tests/basic-tests.ts, packages/parser-css/tests/helpers/mocks.ts, packages/parser-css/tests/interface-tests.ts, packages/parser-html/tests/parser.ts, packages/parser-javascript/src/parser.ts, packages/parser-javascript/tests/tests.ts, packages/utils-tests-helpers/src/hint-runner.ts
Make sure you:
Fix #1956 
Includes a number of improvements across packages already split into dedicated commits.
=> Fix position in reports for CSS and JS in HTML

packages/hint-amp-validator/src/hint.ts, packages/hint-amp-validator/tests/tests.ts, packages/hint-babel-config/tests/is-valid.ts, packages/hint-compat-api/tests/css-next.ts, packages/hint-compat-api/tests/css.ts, packages/hint-compat-api/tests/fixtures/css/appearance-splitted.css, packages/hint-compat-api/tests/fixtures/css/appearance.css, packages/hint-compat-api/tests/fixtures/css/box-flex-prefixes.css, packages/hint-compat-api/tests/html-next.ts, packages/hint-compat-api/tests/html.ts, packages/hint-css-prefix-order/tests/fixtures/interleaved-prefixes.css, packages/hint-css-prefix-order/tests/fixtures/mixed-with-prefixes-last.css, packages/hint-css-prefix-order/tests/fixtures/multi-block.css, packages/hint-css-prefix-order/tests/fixtures/multi-property.css, packages/hint-css-prefix-order/tests/fixtures/prefixed-values-last.css, packages/hint-css-prefix-order/tests/fixtures/prefixes-last-moz.css, packages/hint-css-prefix-order/tests/fixtures/prefixes-last-same-line.css, packages/hint-css-prefix-order/tests/fixtures/prefixes-last-webkit.css, packages/hint-css-prefix-order/tests/tests.ts, packages/hint-doctype/tests/tests.ts, packages/hint-manifest-is-valid/tests/tests.ts, packages/hint-no-protocol-relative-urls/tests/tests.ts, packages/hint-typescript-config/tests/is-valid.ts, packages/hint-typescript-config/tests/no-comments.ts, packages/hint/docs/contributor-guide/how-to/test-rules.md, packages/utils-tests-helpers/src/hint-runner.ts, packages/utils-tests-helpers/src/hint-test-type.ts
Make sure you:
Makes it easier to write tests with correct location
information by allowing tests to provide substrings
representing where a report should occur.
Previously tests had hard-coded locations which were
prone to mistakes due to difficulty visualizing how
they aligned with the actual text in a file.
----
This is fully functional, but I've only updated the tests for two hints so far to make it easier to adjust for feedback. If we like the approach I can convert the rest of our existing test positions before merging.
Pending test updates:
* ~Fix positions in hint-html-checker tests~
=> Chore: Refactor location tests to match similar text

packages/connector-jsdom/src/connector.ts, packages/connector-jsdom/src/resource-loader.ts, packages/extension-browser/src/content-script/connector.ts, packages/hint/src/lib/utils/dom/get-element-by-url.ts, packages/hint/tests/lib/utils/dom/get-element-by-url.ts, packages/utils-debugging-protocol-common/src/debugging-protocol-connector.ts
Make sure you:
Use the base URL of the document to resolve relative URLs for finding elements, not the URL that was requested.
Fix unhandled errors cause by trying to resolve relative URLs against data-uris.
Also fix not found elements due to relative URLs being resolved against the wrong path.
=> Fix: Use correct base URL in getElementByUrl

packages/create-hint/src/create-hint.ts, packages/create-hint/tests/create-hint.ts
Make sure you:
If the user creates a new individual hint, `package.json` will point to
`dist/src/hint.js` instead of `dist/src/index.js` and will no longer
create an `index.js`. This is consistent with the format of the other
hints.
Fix #1916
=> Fix: Point to right entry point

packages/hint-content-type/tests/tests.ts
Make sure you:
`canvas` 2.4.1 has a problem on macOS where it crashes if an svg does
not have dimensions. This sets the dimensions to 1x1
Fix #2113
Ref https://github.com/Automattic/node-canvas/issues/1400
=> Chore: Add dimension to svg in tests

.npmrc
Make sure you:
~For non-trivial changes, please make sure you also:~
Without the `scripts-prepend-node-path` flag, yarn did not use the
node installed using nvm.
Fix #2219
=> Chore: Correct node binary path for nvm installs

packages/connector-jsdom/src/connector.ts
Make sure you:
Under some circumstances, the method to kill all subprocesses in jsdom was not executed because the property `this._window` was not initialized.
rel https://github.com/webhintio/online-service/issues/195
=> Fix: Ensure we are clossing subprocesses in jsdom.

packages/create-hintrc/src/create-hintrc.ts
Remove extra `%` from NPM URL.
Make sure you:
=> Fix broken link to NPM

packages/hint/package.json, packages/utils/package.json, packages/utils/src/network/as-uri.ts, yarn.lock
Make sure you:
`file-url` comes now with its own type definition so `@types/file-url`
is no longer needed. Also `hint` depends on `file-url` which is not
needed any more.
=> Chore: Remove `@types/file-url` and update `import`

packages/utils/README.md, packages/utils/package.json, packages/utils/src/chromium-finder.ts, packages/utils/src/index.ts, packages/utils/src/misc/environment.ts, packages/utils/src/misc/get-platform.ts, packages/utils/tests/chromium-finder.ts
Make sure you:
Fix #2260
I'll probably have to do more changes once I start working on #2139 and #2248 but this should be a good starting point.
=> New: Util `chromium-finder`

packages/utils/src/dom/snapshot.ts
Make sure you:
Some sites (e.g. fossa.com) load libraries which shim parts of the DOM
prototype heirarchy. This leads to `instanceof` checks failing while
attempting to take a snapshot of the DOM.
Switching to use `nodeType` instead of `instanceof` fixes the problem.
=> Fix: Make snapshot resilient to prototype overrides

azure-pipelines/standard.yml
Make sure you:
Run `brew update` in all macOS pipelines. It was missing for PRs and I believe that's the cause where it was failing to install chrome even though the `cask` was updated a day ago.
=> Build: Run `brew update` in all macOS pipelines

packages/hint/src/lib/cli/analyze.ts
Fix #2339
Make sure you:
- ~~[ ] Added/Updated related documentation.~~
- ~~[ ] Added/Updated related tests.~~
Corrects cli link to telemetry page
=> Fix: Correct CLI link to telemetry page

packages/hint-manifest-scoped-urls/.npmrc, packages/hint-manifest-scoped-urls/LICENSE.txt, packages/hint-manifest-scoped-urls/README.md, packages/hint-manifest-scoped-urls/package.json, packages/hint-manifest-scoped-urls/src/hint.ts, packages/hint-manifest-scoped-urls/src/meta.ts, packages/hint-manifest-scoped-urls/tests/tests.ts, packages/hint-manifest-scoped-urls/tsconfig.json, tsconfig.json
=>  New: Add manifest-scoped-urls

packages/hint/src/lib/hint-context.ts, packages/utils/src/report/get-html-code-snippet.ts
=> Fix: Trim source snippets auto-generated from element references

packages/connector-local/src/connector.ts
Make sure you:
`connector-local` didn't got the schema with the other updates. I've marked as `New:`  but maybe it should be `Breaking` as the others so we can start fresh (and catch if something is wrong in the logs?) @antross what do you think?
=> New: Add a `schema` property for validation

packages/utils/src/dom/snapshot.ts, packages/utils/src/types/snapshot.ts, packages/utils/tests/dom/snapshot.ts
Make sure you:
Test bundle: 
[extension-pr2443.zip](https://github.com/webhintio/hint/files/3184266/extension-pr2443.zip)
----
Fix #2427
Aligns with parse5 behavior for parse5-htmlparser2-tree-adapter.
=> Fix: Snapshot template element content as children

packages/configuration-progressive-web-apps/index.json, packages/configuration-progressive-web-apps/package.json, packages/configuration-web-recommended/index.json, packages/configuration-web-recommended/package.json
Make sure you:
I'm also making puppeteer the default connector here. This should hopefully give the user a better experience and less issues with brotli and canvas.
Fix #2254
=> Breaking: Replace `chrome` with `puppeteer`

packages/connector-puppeteer/src/lib/lifecycle.ts, packages/utils-tests-helpers/src/hint-runner.ts
Make sure you:
Linux builds are failing from time to time with timeout navigations
(especially with `no-broken-links`) that go away after a retry. This
increases the Navigation timeout from 30s to 60s.
Ref: https://dev.azure.com/webhint/webhint/_build/results?buildId=4082&view=logs&jobId=9b571771-e73a-56cf-6cd2-9d9b8a35c940&taskId=3fc73644-a427-5aa2-c480-bc83d146d7cc&lineStart=5168&lineEnd=5169&colStart=1&colEnd=1
=> Chore: Increase `timeout`

packages/hint/src/lib/utils/resource-loader.ts
Make sure you:
When running globally (`npx` or `npm create`) the resources where
searched in the global installation folder instead of relative to where
the process is being run. This caused tools such as `npm create hintrc`
to never find any of the resources preinstalled which is not the
expected behavior.
While this might be considered a breaking change, global run with hints
outside the `hint` global folder never worked correctly.
Fix #2263
=> Fix: Correctly find resources when runnning globally

packages/extension-browser/src/_locales/en/messages.json, packages/extension-browser/src/devtools/views/pages/analyze.css, packages/extension-browser/src/devtools/views/pages/analyze.tsx
Fix #2440
Make sure you:
This change add the message "Did you know that..." to the analyzing screen in the browser scanner so people don't get confused by the messages.
=> Fix: Add "Did you know that..." to the analyzing screen

packages/extension-browser/src/devtools/views/controls/progress-bar.css
=> Fix: Remove `!important` for progress bar control

packages/hint-compat-api/src/css.ts, packages/hint-compat-api/tests/css.ts
Make sure you:
When ALL targeted browsers pass for an unprefixed
version of a property, reports for prefixed versions of
that property in the same block are now ignored.
This was not happening before because no entry was
tracked in the reports map for a given block when all
browsers passed.
=> Fix: Ignore prefixed properties when all browsers pass

packages/extension-browser/src/devtools/views/pages/results/hint.css
Make sure you:
Aligns styling of `<summary>` with the HTML standard which uses
`display: list-item` to add the toggle icon. This means the icon
vanishes when changing `<summary>` to `display: inline-block` in
browsers that implement the standard correctly.
Now the desired effect is acheived using `width: max-content`.
=> Fix: Show summary toggle in Firefox

packages/extension-browser/package.json, packages/extension-browser/scripts/drop-persistent-flag.js
Make sure you:
Release version only. Since the flag is ignored other than the warning
it does not need to be removed from debug builds.
Fix #2592
=> Fix: Avoid warning in Firefox about background.persistent

packages/extension-browser/src/background-script.ts
Make sure you:
Found while experimenting with extension permissions. This was logging the error to the console, but the scan still waited until the timeout. 
Note some pages such as the extensions store block extension access entirely without producing an error - those are not covered by this change.
=> Fix: Cancel scan when script injection fails

packages/extension-browser/src/devtools/views/app.base.css, packages/extension-browser/src/devtools/views/pages/config/sections/browsers.tsx, packages/extension-browser/src/devtools/views/pages/results/problem.css
Make sure you:
One fix to allow results to be selected. Another to provide a more relevant default example for customizing target browsers. To be merged as separate commits.
Test bundles:
* Chromium: [webhint-0.0.4.zip](https://github.com/webhintio/hint/files/3303103/webhint-0.0.4.zip)
* Firefox: [webhint-0.0.4.zip](https://github.com/webhintio/hint/files/3303104/webhint-0.0.4.zip)
=> Extension fixes

scripts/check-commit-message.js
=> Fix: Don't allow Breaking commits to span multiple packages

packages/hint-no-html-only-headers/README.md, packages/hint-no-html-only-headers/src/hint.ts, packages/hint-no-html-only-headers/tests/tests.ts
Make sure you:
Fix #2342 
Fix #2349
=> Fix no html only headers

packages/hint-content-type/README.md, packages/hint-content-type/src/hint.ts, packages/hint-content-type/tests/tests.ts
=> New: Allow `application/javascript` for JS resources by default

packages/extension-browser/src/devtools/views/powered-by.tsx
Make sure you:
Resolves #2643 
The webhint version used should be displayed in browser extension next to "powered by webhint" text.
=> New: Show version in browser extension

packages/extension-browser/src/_locales/en/messages.json, packages/extension-browser/src/devtools/views/controls/inspect-button.css, packages/extension-browser/src/devtools/views/controls/inspect-button.icon.svg, packages/extension-browser/src/devtools/views/controls/inspect-button.tsx, packages/extension-browser/src/devtools/views/controls/source-code.css, packages/extension-browser/src/devtools/views/pages/results/header.css, packages/extension-browser/src/devtools/views/pages/results/problem.css, packages/extension-browser/src/devtools/views/pages/results/problem.tsx
Also switch to use overflow-wrap instead of word-break to avoid
breaking words unless necessary.
Fix #2659
Make sure you:
=> New: Update "Inspect Element" icon and location

packages/configuration-web-recommended/index.json
Specifically enables `hint-create-element-svg` to run as part of the
default `configuration-web-recommended`. That hint was already part
of this configuration, but did not run by default since no JavaScript
parse events were being emitted.
Make sure you:
=> Fix: Enable JavaScript parser for related hints

packages/configuration-development/index.json
Fixes error about missing `hint-axe` affecting the VS Code extension.
This configuration already extends `configuration-accessibility` and
does not need to specify `axe` hints directly.
Make sure you:
=> Fix: Remove old `axe` hint reference

packages/hint-axe/scripts/create.js, packages/hint/src/lib/utils/resource-loader.ts
Adapts to the new requirement to use forward slashes `/` in patterns.
Also fixes a confusing reference to `globby.sync`.
Make sure you:
=> Chore: Fix test failures due to `globby` type updates

packages/parser-typescript-config/src/parser.ts, packages/parser-typescript-config/tests/tests.ts
=> Fix: Ignore tsconfig.schema.json files

packages/hint/src/lib/cli/analyze.ts, packages/hint/src/lib/config.ts, packages/hint/src/lib/types/analyzer.ts
Make sure you:
Earlier, `language` of Analyzer was being taken from config file or OS Locale.
Now it is using CLI Options also, if `language` is present in them.
This bug was caught when `packages/hint` test case failed. 
In below screenshot, test case is expecting `en-US` as language of Analyzer. But it happens to be `en-GB`. This is because current logic of loading config in Analyzer is taking language either from config file or OS Locale. This makes the test case execution OS dependent as config file is always null here.
Actually Analyzer should also consider CLI Options being passed. In test cases, we are already passing `language = 'en-US'` as actions (CLIOptions).
=> Fix: Use `language` from `CLI Options` if present

packages/connector-puppeteer/README.md
Also update links to puppeteer documentation to always point to the
latest version.
Fix #2772
Make sure you:
=> Docs: Add documentation for `puppeteerOptions`

packages/connector-puppeteer/src/lib/get-favicon.ts
=> Fix: Error getting favicon with puppeteer in node 8 with headless

packages/extension-vscode/.vscodeignore, packages/extension-vscode/package.json, packages/extension-vscode/src/extension.ts, packages/extension-vscode/src/notifications.ts, packages/extension-vscode/src/server.ts, packages/extension-vscode/src/utils/analytics.ts, packages/extension-vscode/tests/fixtures/mocks.ts, packages/extension-vscode/tests/server.ts, packages/extension-vscode/tests/utils/analytics.ts, packages/hint/docs/user-guide/telemetry/summary.md
Test package: [vscode-webhint-1.0.5.zip](https://github.com/webhintio/hint/files/3454062/vscode-webhint-1.0.5.zip)
Adds two new events: `vscode-open` and `vscode-save`
corresponding to when a user first opens a file and each time it gets
saved, respectively. Hint status is calculated on save by comparing the
initial open state to the most recent scan before saving.
Fix #2712
Make sure you:
=> New: Add telemetry with user opt-in

.eslintignore, packages/hint/src/lib/cli/analyze.ts, packages/hint/tests/lib/cli/analyze.ts
=> Fix: Prune UserConfig data

packages/create-hint/package.json, packages/create-hint/src/handlebars-utils.ts, packages/create-hint/src/shared-templates/package.hbs, packages/create-hint/src/utils.ts
Make sure you:
- ~~[ ] Added/Updated related tests.~~
This PR improves the process of creating new hint in main repo in following two ways:
1. It loads package versions from `create-hint/package.json` while creating new hint.
As package versions in `package.json` will always remain updated, it seems good idea to load versions from it instead of updating manually in template file.
Thoughts?
2. ~~`webpack` is added to create-hint build script. When user run `npm create hint` in `hint/packages` of main repo, it doesn't work. It requires to run `webpack` after `yarn && yarn build` to create executable `create-hint` binary.~~
This is removed as test cases are failing if we add webpack step in build script.
Fix: #2657
=> Fix: Load latest versions from package in `create-hint` templates

packages/hint-create-element-svg/src/hint.ts, packages/hint-create-element-svg/tests/tests.ts
Fix #2706
Make sure you:
~~- [ ] Added/Updated related documentation.~~
=> Fix: False positives for React.createElement

packages/hint-axe/src/util/axe.ts, packages/hint-axe/tests/color.ts
Includes additional check messages from axe core when data is
associated with those messages. Some examples include the
calculated color contrast ratio and invalid values for ARIA attributes.
Fix #2746
Make sure you:
=> New: Include additional check data from axe when available

packages/hint-scoped-svg-styles/.npmrc, packages/hint-scoped-svg-styles/LICENSE.txt, packages/hint-scoped-svg-styles/README.md, packages/hint-scoped-svg-styles/package.json, packages/hint-scoped-svg-styles/src/_locales/en/messages.json, packages/hint-scoped-svg-styles/src/hint.ts, packages/hint-scoped-svg-styles/src/meta.ts, packages/hint-scoped-svg-styles/tests/fixtures/elements-inside-unrelated-svg.html, packages/hint-scoped-svg-styles/tests/fixtures/elements-outside-svg.html, packages/hint-scoped-svg-styles/tests/fixtures/valid-page.html, packages/hint-scoped-svg-styles/tests/hint.ts, packages/hint-scoped-svg-styles/tsconfig.json, packages/utils/src/dom/html.ts, packages/utils/tests/dom/html.ts, tsconfig.json, yarn.lock
Make sure you:
Added new hint `scoped-svg-styles`.
Resolves: #2729
=> Add hint `hint-scoped-svg-styles` to warn about styles bleeding across inline SVGs

packages/hint-highest-available-document-mode/src/hint.ts
Make sure you:
In `hint-highest-available-document-mode`, `getXUACompatibleMetaElements` function is defined to filter out elements from given `elements` that have attribute `http-equiv` with value `x-ua-compatible`.
It can be replaced by using direct selectors. Selectors with attributes and values are now supported by `querySelectorAll`.
So we can use `meta[http-equiv=x-ua-compatible i]` selector to get `XUACompatibleMetaElements`.
`i` in the selector is to ignore case.
Resolves: #2033
=> Chore: Remove iterating over elements and use direct selector

packages/formatter-html/src/assets/js/scan/scanner-common.js
Make sure you:
This bug got introduced because of a small change.
Earlier `<span class="permalink-content">` was inside the copy button, so logic was to find closest parent element with class `.permalink-copy`.
But in [this commit](https://github.com/webhintio/hint/commit/f0438eb0121c96a21c67619477c03b06ec8ac7a8), `<span>` was taken out for a good reason :). But logic start breaking as there is no parent element with class `.permalink-copy`.
Please review the fix.
Fix: #2705
=> Fix check mark not appearing after copy to clipboard in `formatter-html`

packages/create-hintrc/tests/create-hintrc.ts, packages/create-parser/tests/new-parser.ts
=> Fix: Stub calls to Application Insights for tests

packages/hint-minified-js/src/hint.ts, packages/hint-minified-js/tests/tests.ts
Include reference to `<script>` element in reports for inline scripts.
Also ignore scripts below 1KB (which are prone to false-positives).
Fix #2898
Ref #2645
Make sure you:
=> Fix: Improve minified JavaScript reports

packages/hint/package.json, packages/hint/src/lib/cli/analyze.ts, packages/hint/tests/lib/cli/analyze.ts
=> Fix: Using `formatter-stylish` in CI by default.

packages/hint/docs/contributor-guide/index.md, packages/hint/docs/user-guide/concepts/configurations.md, packages/hint/docs/user-guide/concepts/connectors.md, packages/hint/docs/user-guide/concepts/formatters.md, packages/hint/docs/user-guide/concepts/hints.md, packages/hint/docs/user-guide/concepts/parsers.md
This PR impacts the docs in two discrete ways.
1. Copy editing for clarity. i'd love to see some form of those changes get merged regardless and look forward to y'all's review. One specific detail is reserving ` backticks exclusively for indicating code, instead of using them for terminology, filenames, and proper nouns. I could go back and use italics for some of the terminology, my focus for this PR was strictly readability.
2. As is currently being discussed in #2774, using full package names in .hintrc. This could be split into two PRs, but I'd rather wait to see how that conversation goes since initially all these changes were worked as one problem.
Make sure you:
- Update hintrc config …
=> Docs: Clarify package name usage; light copy edits

packages/extension-vscode/.vscode/launch.json, packages/extension-vscode/.vscodeignore, packages/extension-vscode/package.json, packages/extension-vscode/src/extension.ts, packages/extension-vscode/src/utils/packages.ts, packages/extension-vscode/webpack.config.js, scripts/lint-dependencies.js, yarn.lock
Reduces extension size and unblocks sharing utilities
with other parts of webhint.
Fix #2803
Make sure you:
=> Chore: Bundle VS Code extension with webpack

packages/extension-browser/src/content-script/connector.ts, packages/extension-browser/src/content-script/fetcher.ts, packages/extension-browser/src/content-script/set-fetch-type.ts, packages/extension-browser/src/devtools/utils/network.ts, packages/extension-browser/tests/content-script/fetcher.ts
Make sure you:
Explicitly delete the cache and any service worker data before reloading. 
Fix #2928
Bundles for testing:
[chromium 2019-09-09](https://github.com/webhintio/hint/files/3592792/webhint-0.0.7.zip)
[firefox 2019-09-09](https://github.com/webhintio/hint/files/3592794/webhint-0.0.7.zip)
=> Fix: Clear cache and service worker data on reload

packages/extension-browser/scripts/copy-version.js
Now shows the version number in the UI instead of placeholder text.
This regressed when I integrated the extension into our release script.
Was showing
`Powered by webhint v(set by scripts/copy-version.js)`
Instead of 
`Powered by webhint v0.0.7`
Make sure you:
=> Fix: Copy version to manifest bundled with webpack

packages/hint-compat-api/package.json, packages/hint-compat-api/src/css.ts, packages/hint-compat-api/src/html.ts, packages/hint-compat-api/src/utils/browsers.ts, packages/hint-compat-api/tests/css.ts, packages/hint-compat-api/tests/html.ts, packages/hint-compat-api/tests/utils/browsers.ts, packages/utils/README.md, packages/utils/scripts/mdn-browser-compat-data.js, packages/utils/src/compat/browsers.ts, packages/utils/src/compat/cache.ts, packages/utils/src/compat/css.ts, packages/utils/src/compat/html.ts, packages/utils/src/compat/support.ts, packages/utils/tests/compat/browsers.ts
Make sure you:
Names are pulled from mdn-browser-compat-data.
Versions now focus on when a feature was added/removed.
Includes plumbing additional data through existing compat utilities.
Fix #2896
=> Improve browser names/versions reported by hint-compat-api

packages/hint/src/bin/hint.ts, packages/hint/src/lib/cli/analyze.ts, packages/hint/tests/lib/cli/analyze.ts, packages/utils/src/app-insights.ts
Make sure you:
Send `CIRun` events when the user gives permission for telemetry instead
of `FirstRun` so it is easier to know when there are new users and how
many times it is used from CI.
Fix #2962
=> Fix: Track `FirstRun` events in CI differently

packages/extension-browser/src/_locales/en/messages.json, packages/extension-browser/src/devtools/views/controls/external-link.css, packages/extension-browser/src/devtools/views/pages/results/category-summary.tsx, packages/extension-browser/src/devtools/views/pages/results/category.css, packages/extension-browser/src/devtools/views/pages/results/hint.css, packages/extension-browser/src/devtools/views/pages/results/hint.tsx, packages/extension-browser/src/devtools/views/pages/results/message-group.css, packages/extension-browser/src/devtools/views/pages/results/message-group.tsx, packages/extension-browser/src/devtools/views/pages/results/problem.css, packages/extension-browser/src/devtools/views/pages/results/problem.tsx
Make sure you:
Also update layout of related controls to prefer controlling spacing
from parent controls instead of children. This makes child controls
easier to re-use without breaking layout.
Fix #2970
=> New: Group hint reports with the same message text

packages/hint-validate-set-cookie-header/tests/tests.ts
Make sure you:
I tried them on WSL which has headless on by default and tests are passing now: 
Fix #439
=> Chore: Re-enable `no-insecure-cookies` tests on `puppeteer`

packages/utils/src/packages/load-resource.ts
Previously names like 'css' could match local folders.
Now relative paths must be written like `./css`.
Make sure you:
=> Fix: Disallow simple names as filesystem paths

packages/extension-vscode/src/utils/analyze.ts, packages/extension-vscode/src/utils/prompts.ts, packages/extension-vscode/src/utils/webhint-packages.ts, packages/extension-vscode/tests/utils/webhint-packages.ts
Previously a prompt to install to a project would delay
loading any copy of webhint until the user responded,
causing the experience to feel broken once the
notification was automatically hidden.
Make sure you:
Opening as a draft while I finish adding tests.
=> Fix: Load shared webhint when prompting to install locally

packages/hint-css-prefix-order/package.json, packages/hint-css-prefix-order/src/hint.ts, packages/hint-css-prefix-order/tests/fixtures/prefixes-nested-blocks.scss, packages/hint-css-prefix-order/tests/tests.ts
=> Fix: Avoid duplicate reports in nested blocks

packages/extension-browser/src/devtools/views/app.base.css, packages/extension-browser/src/devtools/views/app.fluent.css, packages/extension-browser/src/devtools/views/app.photon.css, packages/extension-browser/src/devtools/views/controls/source-code.css, packages/extension-browser/src/devtools/views/pages/analyze.css
Make sure you:
Shadow styles used in the extension are defined as CSS variables in `app.fluent.css` and `app.photon.css`
=> Chore: Shadow styles as CSS variables in extension

packages/extension-vscode/package.json, packages/extension-vscode/src/utils/analyze.ts, packages/extension-vscode/src/utils/packages.ts, packages/extension-vscode/src/utils/webhint-packages.ts, packages/extension-vscode/tests/utils/packages.ts, packages/extension-vscode/tests/utils/webhint-packages.ts
Make sure you:
* Create a package.json for shared webhint so npm pruning works
* Use `@latest` tag with install to ensure most recent version is used
* Only update shared webhint after initial load, not config changes
* Update shared webhint before retrying when load fails
* Raise bundle size limit slightly to account for new code
Fix #2998
Test bundle for side-loading: [vscode-webhint-1.3.2.zip](https://github.com/webhintio/hint/files/3704099/vscode-webhint-1.3.2.zip)
=> Fix: Ensure shared webhint installs/updates correctly

.dependabot/config.yml, packages/connector-local/package.json, packages/connector-puppeteer/package.json, packages/create-hint/package.json, packages/create-hintrc/package.json, packages/create-parser/package.json, packages/create-parser/src/shared-templates/package.hbs, packages/extension-browser/package.json, packages/extension-browser/tests/background-script.ts, packages/extension-browser/tests/content-script.ts, packages/extension-vscode/package.json, packages/formatter-codeframe/package.json, packages/formatter-excel/package.json, packages/formatter-html/package.json, packages/formatter-json/package.json, packages/formatter-stylish/package.json, packages/formatter-summary/package.json, packages/hint/package.json, packages/parser-css/package.json, packages/parser-javascript/package.json, packages/parser-less/package.json, packages/parser-package-json/package.json, packages/parser-sass/package.json, packages/parser-typescript-config/package.json, packages/parser-webpack-config/package.json, packages/utils/package.json, yarn.lock
=> Chore: Update proxyquire

packages/connector-jsdom/src/connector.ts, packages/connector-jsdom/src/evaluate-resource-loader.ts, packages/connector-jsdom/src/evaluate-runner.ts
=> Fix: Unhandled promise rejections when self-signed in jsdom

packages/create-hint/src/templates/meta.ts.hbs, packages/create-hint/src/templates/partial-event-code.hbs
Make sure you:
The `create-hint` template has some old/broken urls in the comments. I updated the urls to point to the pages that I think they should:
- about schema: https://webhint.io/docs/contributor-guide/how-to/hint/#the-meta-property
- how to hint: https://webhint.io/docs/contributor-guide/how-to/hint/
Feel free to update the links if I got the pages wrong. Thanks!
=> Fix: Template broken url

packages/hint/docs/user-guide/configuring-webhint/browser-context.md
Make sure you:
Fix minor typo on 'Browser Configuration' docs page
=> Fix minor typo on 'Browser Configuration' docs page

release/tasks/validate-environment.ts
Make sure you:
Fix #3172 
Changed to validate temporary against my fork and tested with `servicing` and `bla` branches:
=> Build: Enable releasing from `servicing` branch

package.json, packages/configuration-development/index.json, packages/configuration-development/package.json, packages/extension-browser/src/shims/acorn-jsx-walk.ts, packages/extension-browser/src/shims/acorn-jsx.ts, packages/extension-browser/webpack.config.js, packages/extension-vscode/package.json, packages/parser-javascript/package.json, packages/parser-javascript/src/parser.ts, packages/parser-javascript/src/types.ts, packages/parser-javascript/src/walk.ts, packages/parser-javascript/tests/tests.ts, packages/parser-jsx/.npmrc, packages/parser-jsx/LICENSE.txt, packages/parser-jsx/README.md, packages/parser-jsx/package.json, packages/parser-jsx/src/parser.ts, packages/parser-jsx/tests/tests.ts, packages/parser-jsx/tsconfig.json, scripts/lint-dependencies.js, tsconfig.json, yarn.lock
Make sure you:
Fix #2889 
* Allows JS hints such as `hint-create-element-svg` to run against `*.jsx` files.
* Also allows HTML hints such as `hint-button-type` to run against `JSX` content.
* Introduces the concept of fragment documents and expressions to represent template content.
* Strips JSX libraries when bundling `extension-browser`
=> New: Add support for JSX

scripts/lint-dependencies.js
Make sure you:
This PR add supports to `lint-dependencies.js` for:
```
import {
a,
b
} from 'package';
```
=> Build: Update lint-dependencies to support multilines imports

packages/hint-typescript-config/src/helpers/config-checker.ts, packages/hint-typescript-config/src/target.ts, packages/hint-typescript-config/tests/consistent-casing.ts, packages/hint-typescript-config/tests/fixtures/strict/strict-false/tsconfig.json, packages/hint-typescript-config/tests/fixtures/target/extends-overrides/tsconfig.json, packages/hint-typescript-config/tests/fixtures/target/extends/tsconfig.json, packages/hint-typescript-config/tests/fixtures/target/no-target-extends-target/tsconfig.json, packages/hint-typescript-config/tests/fixtures/target/no-target-extends/tsconfig.json, packages/hint-typescript-config/tests/import-helpers.ts, packages/hint-typescript-config/tests/is-valid.ts, packages/hint-typescript-config/tests/strict.ts, packages/hint-typescript-config/tests/target.ts, packages/parser-typescript-config/README.md, packages/parser-typescript-config/src/parser.ts, packages/parser-typescript-config/src/types.ts
Make sure you:
Improvements in a couple of edge cases:
- `target` was pointing to `{` because it did not do the right search
- when a configuration `extends` but none of the files had a required
property, `extends` got underlined because it was set as the
`alternatePath`. With the improvements in the node search this is no
longer needed.
=> Fix: Edge error locations when using `extends`

packages/hint/docs/user-guide/development-flow-integration/circleci.md, packages/hint/docs/user-guide/development-flow-integration/summary.md, packages/hint/docs/user-guide/development-flow-integration/travisci.md
Make sure you:
Fix #2713
Fix #2776
=> Docs: How to integrate on CircleCI and Travis CI

packages/extension-vscode/src/utils/problems.ts, packages/hint/src/lib/cli/analyze.ts, packages/hint/src/lib/config/config-hints.ts, packages/hint/src/lib/config/config-schema.json, packages/hint/src/lib/hint-context.ts, packages/hint/tests/lib/config/config-hints.ts, packages/utils/src/types/config.ts, packages/utils/src/types/problems.ts
Make sure you:
It turns out that the new proposed format is kind of already supported but not documented.
We can use the shorthand version to declare hints:
```json
{
"hints": [
"hint-a",
"hint-b",
["hint-a", { "config": "a" }]
]
}
```
On top of that we also have the option to prefix the hint with `-` to disable it (e.g. `-hint-a`), as well as `hint-a:off`. 
The option of `on|off` is still not implemented and right now I'm not sure we should with all the other options we have already supported. I'm thinking we should just remove some of the options (such as `hint-a:warn`, but keep `hint-a:off`) when we are ready for a breaking change.
This PR also: 
* adds the `information` and `hint` severity levels that match the ones in VS Code. 
* …
=> severityThreshold + respect user's configuration

packages/utils-tests-helpers/src/hint-runner.ts
Make sure you:
Likely superseded by #3297, but wanted to call this out separately in case we want to either (1) merge this fix first or (2) ensure this fix is covered by that PR.
Basically the way the checks were structured in `validateResults` allowed `severity` to be ignored if a `position` property was also part of the expected report as the block for `position` would return whether or not there was a match. Moving the `severity` check earlier fixes that issue.
=> Chore: Ensure severity gets validated in tests with position data

packages/extension-vscode/src/server.ts, packages/extension-vscode/src/utils/analytics.ts, packages/extension-vscode/src/utils/analyze.ts, packages/extension-vscode/tests/utils/analytics.ts
Early telemetry shows a large number of different file extensions can be
mapped to one of the language types webhint registers for. Switching to
use the language ID from VS Code should help simplify this metric.
Make sure you:
=> Fix: Use VS Code language ID to reduce file type telemetry noise

packages/hint-meta-theme-color/src/hint.ts, packages/hint-meta-theme-color/tests/tests.ts
=> New: Default severity for `hint-meta-theme-color`

packages/formatter-html/src/result.ts
=> Fix: Update formatter html to support new severities

packages/create-hintrc/src/create-hintrc.ts, packages/hint/src/lib/config/config-schema.json, packages/hint/tests/lib/config/config-validator.ts
Make sure you:
This configuration is only for internal consumption to get easy access
to all the documentation and should never be used by a user as it can
cause problems when extending from it.
This PR filters it when running `npm init hintrc` and verifies the
`.hintrc` doesn't `extends` from it.
Fix #3097
=> Fix: Hide `configuration-all` from the user

packages/extension-browser/src/devtools/views/pages/config/sections/severities.tsx
Fix #3375
Make sure you:
For selfhosting:
Chromium:
[webhint-1.2.1.zip](https://github.com/webhintio/hint/files/3872001/webhint-1.2.1.zip)
Firefox:
[webhint-1.2.1.zip](https://github.com/webhintio/hint/files/3872002/webhint-1.2.1.zip)
=> Fix: Information position in minimum hint severity section

packages/hint-css-prefix-order/src/hint.ts, packages/utils-css/README.md, packages/utils-css/src/get-css-code-snippet.ts, packages/utils-css/tests/fixtures/report.css, packages/utils-css/tests/get-css-code-snippet.ts
=> Fix: CSS prefix order does not have full code snippet

packages/extension-vscode/src/utils/analytics.ts, packages/extension-vscode/src/utils/analyze.ts, packages/extension-vscode/src/utils/prompts.ts, packages/extension-vscode/src/utils/webhint-packages.ts, packages/extension-vscode/tests/utils/problems.ts, packages/extension-vscode/tests/utils/prompts.ts, packages/extension-vscode/tests/utils/webhint-packages.ts
Make sure you:
The VS Code extension could end up breaking `node_modules` in the
workspace or the global shared folder. This was caused because we were
installing `hint@latest` in the workspace and because that process
took too long and the user might closed the editor before it was
ended.
To avoid that we now let the user manage their own `hint` installation
in the workspace, no more prompting about installation. If no version
can be loaded from the workspace, the shared one (`hint@latest`) will
be used.
Also, the shared version is updated after 2 minutes instead of
immediately and only if the shared version has been successfully
loaded.
If the user already has a workspace version there is no point in
updating the shared one as it will …
=> Fix: Stability issues with VS Code extension

packages/utils/src/npm.ts
=> Breaking: Fix getUnofficialPackages name and search

packages/hint-apple-touch-icons/tests/tests.ts, packages/utils-tests-helpers/src/hint-runner.ts
Make sure you:
When validating a report `hint-runner` checked all the properties at the
same time. This made difficult to debug what property was not matching,
and what was the expected value.
Now `hint-runner` provides more information for each of the properties
that validates, and comparing to the closest matched report.
Old behavior:
New behavior:
=> New: Improve error messages when running tests

packages/utils-create-server/package.json, yarn.lock
The one by dependabot is broken and it looks like we have to update another dependency per https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40138#issuecomment-550325070
=> Upgrade: Bump @types/express from 4.17.1 to 4.17.2

packages/extension-vscode/src/utils/analyze.ts
Make sure you:
Using and old version of webhint, the vscode extension throw an exception in the method `getUserConfig`, and the extension stop working. Adding that method to the `try/catch` block, if something fails, it will prompt a message to continue using the shared version of webhint.
=> Fix: Add getUserConfig to the try/catch block

packages/hint/src/lib/config.ts, packages/hint/tests/lib/config.ts, packages/hint/tests/lib/fixtures/valid/array-hints.json
=> Fix: Normalize hints when extending

azure-pipelines/full.yml, azure-pipelines/standard.yml
Make sure you:
Linux and macOS are failing a lot in CI. Looks like the problem is the current version of the browser with puppeteer. Using the beta version of the browser looks like fix the issue.
=> Fix: Use chrome beta for builds

packages/utils-connector-tools/src/normalize-headers.ts, packages/utils-connector-tools/tests/normalize-headers.ts
Make sure you:
CDP combines duplicated headers with `\n` while `request` follows
[HTTP
RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).
This changes the behavior to be `,` separated and remove duplicated
values.
Fix #750
=> Fix: Normalize duplicate headers

packages/utils-json/src/parse-json.ts, packages/utils-json/tests/parse-json.ts
=> Fix: Increase coverage for json-parser

packages/extension-vscode/src/utils/process.ts, packages/hint-html-checker/src/hint.ts, packages/hint-html-checker/tests/tests.ts, packages/hint-image-optimization-cloudinary/tests/tests.ts, packages/hint-no-broken-links/src/hint.ts, packages/hint-strict-transport-security/tests/_common.ts, packages/utils-connector-tools/src/requester.ts, packages/utils-connector-tools/tests/requester.ts, packages/utils/src/npm.ts, packages/utils/tests/async-wrapper.ts
=> Fix: Return an Error instead of an string when rejecting

packages/extension-browser/src/devtools/utils/storage.ts
Make sure you:
Fall back to non-persistent in-memory cache if `localStorage` is not available.
Fixes #3494
chromium: [webhint-2.0.3.zip](https://github.com/webhintio/hint/files/4172602/webhint-2.0.3.zip)
=> Fix: Check for localStorage availability

packages/hint-no-protocol-relative-urls/src/hint.ts, packages/hint-no-protocol-relative-urls/tests/_generate-tests.ts
Make sure you:
Allow no-protocol-relative-urls like "//host_name_to_prefetch.com" when rel="dns-prefetch" is specified.
Fixes #3505
=> Fix: Allow //-urls on dns-prefetch

packages/hint-validate-set-cookie-header/src/hint.ts, packages/hint-validate-set-cookie-header/tests/tests.ts
Make sure you:
Correctly detect disallowed backslash (`\`) characters in cookie name or value.
Also allows accidentally disallowed forward slash in cookie value.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Directives
> [cookie name] must not contain a separator character like the following: 
`( ) < > @ , ; : \ " / [ ] ? = { }`.
> [cookie value can be any charachter] excluding control characters, Whitespace, double quotes, comma, semicolon, and backslash
=> Fix: Detect invalid backslash in cookie

packages/connector-puppeteer/README.md, packages/connector-puppeteer/src/lib/chromium-finder.ts, packages/connector-puppeteer/tests/actions.ts, packages/connector-puppeteer/tests/authentication.ts, packages/connector-puppeteer/tests/chromium-finder.ts, packages/connector-puppeteer/tests/collect.ts, packages/connector-puppeteer/tests/events.ts, packages/connector-puppeteer/tests/fetch-content.ts, packages/connector-puppeteer/tests/invalid-url.ts, packages/connector-puppeteer/tests/request-response.ts, packages/extension-browser/tests/webhint.ts, packages/utils-tests-helpers/package.json, packages/utils-tests-helpers/src/hint-runner.ts
Make sure you:
Expand the cases where webhint will "just work" by allowing it to
use the version of Chromium bundled with a local puppeteer
installation if one is available.
This will also fix current CI issues on Mac which are failing due to
an inability to find a Chrome installation (puppeteer is present).
=> New: Try puppeteer's Chromium if no browser is specified

package.json, yarn.lock
This reverts commit d86137eae6cb1e7d0f9fcee17962191cec684620
which caused publishing of pre-built resources to fail.
Make sure you:
=> Chore: Revert "Upgrade: Bump @octokit/plugin-throttling from 2.7.0 to 3.2.0"

packages/utils-dom/src/globals.ts, packages/utils-dom/tests/globals.ts
Make sure you:
Ignore if setting a global fails to allow the rest to succeed.
E.g. `self` is set in tests, but cannot be set in real workers.
=> Fix: Handle globals which cannot be overriden

packages/hint-compat-api/tests/html.ts, packages/utils-compat-data/package.json, packages/utils-compat-data/src/browsers.ts, packages/utils-compat-data/src/css-types.ts, packages/utils-compat-data/src/css.ts, yarn.lock
Make sure you:
Includes updating `utils-compat-data` to adapt to MDN schema changes.
Also updates `hint-compat-api` tests to account for Edge 79+.
Supersedes #3598
=> Update MDN browser compat data to 1.0.12

packages/utils-worker/README.md, packages/utils-worker/src/shared/types.ts, packages/utils-worker/src/webhint.ts, packages/utils-worker/tests/integration.ts
Make sure you:
This change introduces a `defaultHintSeverity` configuration option. Most notably it can be set to `"off"` to allow consumers of the worker to explicitly choose when to enable newly added hints.
=> New: Allow disabling included hints by default

packages/hint/docs/user-guide/api/using-api.md
Not sure about this. But shouldn't the output of `webhint.analyze` be named `results` instead of `result`. Nothing wrong with the current name, but when iterating over the results later on in the page, the name `results` is used.
=> Changed variable name to results

packages/extension-browser/src/devtools/views/controls/valid-input.css, packages/extension-browser/src/devtools/views/pages/config.css
This should fix #3528.
Using CSS grid minmax, we can make the various columns
in the config page be at least some predefined width that
avoids poor wrapping of form fields, and at most take all
the size they need.
Now, to avoid them stretching too wide and becoming hard to
read, I preserved the max-width that was already there, but
moved it to the parent element to avoid conflicting with
the auto-fit logic (see below), as this was causing overflow.
We're using auto-fit to make the number of columns adapt to
the available space.
=> Fix: Better wrapping logic for config page

packages/parser-jsx/src/parser.ts, packages/parser-jsx/tests/tests.ts
Make sure you:
This changes follows [the recommendation][1] from @antross to wrap the `{expression}` placeholders parented to lists (`<ul>/<ol>`) in list items `<li>`.
This avoids a false-positive hint failure that the lists contain non-list items.
[1]: https://github.com/webhintio/hint/issues/3486#issuecomment-592649518
Fixes #3486
=> Fix: Wrap some JSX expressions placeholders in list items

packages/hint-no-disallowed-headers/src/_locales/en/messages.json, packages/hint-no-disallowed-headers/src/hint.ts, packages/hint-no-disallowed-headers/tests/tests.ts
This PR should fix #1096.
It adds warnings for the following HTTP response headers:
* Expires
* Host
* P3P
* Pragma
* Via
* X-Frame-Options
* X-UA-Compatible
These were added based on https://www.fastly.com/blog/headers-we-dont-want.
Instead of adding these headers to the existing list of disallowed headers, I added specific checks for these ones. The idea is, this way, we can have specific messages for each of them.
I created a couple of preliminary commits to prepare the code for this, then added the logic for this in a third commit, and finished adding all warnings in a 4th commit.
Finally, I made sure the ignored headers, as configured by users, would also ignore these special headers.
=> Add a few special disallowed headers

packages/utils-dom/src/node.ts
The backing ElementData lists <template> content as children to align
with parse5 behavior. However, this should not be exposed in the
childNodes collection of Node instances. Fixed by filtering out
DocumentFragment instances when returning childNodes.
- - - - - - - - - - - - - - - - - - - - -
Fix #3781
Make sure you:
=> Fix: Handle DocumentFragment under <template>

packages/hint-compat-api/src/css.ts, packages/hint-compat-api/tests/css.ts, packages/hint-compat-api/tests/fixtures/css/subgrid.css
This is a fix proposal for #3479. There are multiple ways for doing this, and the code for it is deviating a bit from the simple AST node visiting logic, so let me know if you have a better idea.
---
Until now, if a CSS property was not supported on at least one browser
the `compat-api/css` hint would not go any further and would report this.
With this change, the hint now checks if at least some browsers did
support the property name, and if so then checks the value on those browsers
too.
This means that something like `grid-template-rows:subgrid` would lead
to 2 reports:
* one for `grid-template-rows` on browsers that don't support it like IE,
* and one for `grid-template-rows:subgrid` on browsers that do support the property
but not this particular value (like Edge 16).
=> Fix: Correctly drill down to CSS values when needed

packages/utils-telemetry/package.json, packages/utils-telemetry/src/index.ts, packages/utils-telemetry/src/telemetry-api.ts, packages/utils-telemetry/tests/telemetry-api.ts
=> New: Add endpoint/data contract to log telemetry to internal api

packages/extension-browser/src/devtools/views/pages/results/header.css
If a report is generated on a site with a very long URL, horizontal
overflow can happen.
We want to avoid this as it forces users to scroll horizontally to
reveal the content.
To do this, we make sure the header text can break anywhere.
Fix #3587
=> Fix: Break header text anywhere needed

packages/utils-dom/src/htmldocument.ts, packages/utils-dom/tests/htmldocument.ts
Make sure you:
This change improves `querySelector` best case performance from O(N) to O(1).
Previously `querySelector` called `querySelectorAll` which had a best case of O(N) traversing all nodes in the DOM (passed in via `_document.children`).
The new implementation re-uses the css-select query cached (shared with `querySelectorAll`) and then leverages `cssSelect.selectOne` which internally leverages [domUtil's `findOne`][1] which has the improved performance (over `findAll`).
[1]: https://github.com/fb55/domutils/blob/d7d349c25f78a50cc3f29d9e83f86cbbcf93b2a9/src/querying.ts#L75
=> Fix: Improve utils-dom querySelector perf by using cssSelect.selectOne

packages/utils-dom/src/htmldocument.ts
Make sure you:
This change prefers `querySelector` over `querySelectorAll` in utils-dom.
This is semantically more correct (better expresses the intent of the code) and leverages the upcoming performance improvement in #3861
=> Chore: Prefer querySelector over querySelectorAll

packages/hint-axe/src/util/axe.ts
Make sure you:
This change improves the performance of hint-axe by using `pageDOM.querySelector` instead of `HintContext.querySelectorAll`. The latter will stop DOM traversal after the first match: best case O(1), the former always does complete DOM traversal: best case O(N).
The typing changed to include `undefined` however this is was the case before because the zero index of an empty array is `undefined`.
=> Fix: Improve perf by using pageDOM.querySelector in hint-axe

packages/utils-dom/src/cached-css-selectors.ts, packages/utils-dom/src/get-compiled-selector.ts, packages/utils-dom/src/htmldocument.ts, packages/utils-dom/src/htmlelement.ts, packages/utils-dom/tests/htmlelement.ts
Make sure you:
This change improves the performance of `utils-dom` by refactoring `Element.matches`.
| before (ms) | after (ms) |
| ------------  | ---------- |
|    0.7199      |   0.7000   |
| before (ms) | after (ms) |
| ------------  | ---------- |
|    +60000    |  16.4900  |
_Previously cnn.com could take minutes to complete._
The problem was matches relied on querySelectorAll which will always check every dom node O(N). Now we compile the selector  test function from `css-select` directly and invoke it on the current element O(1). This performance is not bottlenecked by `compile`.
This change also pulls `CACHED_CSS_SELECTORS` into a shared module used by `htmldocument.ts` and `htmlelement.ts`,
Close #3904
=> Chore: Improve utils-dom perf with matches() refactor

packages/connector-puppeteer/src/lib/chromium-finder.ts
Make sure you:
Ref https://github.com/webhintio/hint/issues/3900 This affected Mac computers. No paths are found even though the correct browsers are installed.
The fix:
* For grep, I removed the $. As seen below, the path doesn't end in .app. So this entry will never get included if we use $.
* For awk, I updated the print to provide us only index 2 and 3
from this -> `path:     /Applications/Google Chrome.app (0x2134)`
to this     ->`/Applications/Google Chrome.app`
```
const lines = execSync(
`${LSREGISTER} -dump` +
` | grep -i '\.app'` + // eslint-disable-line
` | awk '{print $2,$3}'`)
.toString()
.split(newLineRegex);
```
I am not familiar with your testing framework nor the proper setup to run such. But I am finally able to run …
=> Fix: Grep AWK path accounting for suffix

packages/hint/src/lib/analyzer.ts, packages/hint/tests/lib/analyzer.ts
Make sure you:
- n/a Added/Updated related documentation.
Fixes #3910
Formatters need to know which hints were used during analyze, and so by including the `Analyzer.resources` when calling formatters, they can then display only the categories that were actually used.
=> Include Analyzer instance resources when calling formatters

packages/connector-puppeteer/src/lib/chromium-finder.ts
Make sure you:
I noticed a problem when running the latest version of the puppeteer connector on macOS (Mojave in my case). It couldn't find Chrome anymore. After some tweaking I could make it work by adding the missing $ sign to the awk expression. Unfortunately I don't know enough about awk to say if this is a bug or just a new syntax which does not yet work on Mojave.
Feel free to close this pull request if the missing $ sign was intended.
=> Fix: Add missing $ prefix to awk expression

packages/hint-no-disallowed-headers/README.md, packages/hint/docs/user-guide/server-configurations/apache.md, packages/hint/docs/user-guide/server-configurations/iis.md
In PR #3776 I added a few new disallowed HTTP headers, however I did not
update the docs at that points. So this new commit fixes that mistake by
updating both the hint-no-disallowed-headers's README as well as the
server configuration pages in the user guide.
Fix #3922.
=> Docs: Add missing disallowed headers to the docs

packages/hint/src/lib/types/analyzer.ts
Make sure you:
Fix missing `UserConfig` type from hint (#3952) by adding `export type { UserConfig } from '@hint/utils';` to the analyzer types.
=> Fix: UserConfig type not exported by hint

.vscode/launch.json
Make sure you:
VS Code has a custom launch config that is different from our normal config when running tests. We were getting the default ava timeout of 10s, making stepping through the debugger nearly impossible. Fixed by extending the timeout to five minutes when launched from VS Code.
=> Chore: Fix VS Code debugging of ava tests timing out after 10s

packages/hint-babel-config/README.md, packages/hint-compat-api/README.md, packages/hint-typescript-config/README.md, packages/hint-webpack-config/README.md, packages/hint/README.md
Make sure you:
Some links on the following npmjs.org pages 404.
- https://www.npmjs.com/package/hint/v/6.0.7#further-reading
- https://www.npmjs.com/package/@hint/hint-compat-api/v/4.3.5#hints
- https://www.npmjs.com/package/@hint/hint-babel-config/v/2.4.6#hints
- https://www.npmjs.com/package/@hint/hint-typescript-config/v/2.4.6#hints
- https://www.npmjs.com/package/@hint/hint-webpack-config/v/2.4.6#hints
This is caused by https://github.com/npm/marky-markdown/issues/449
The workaround is to provide fully qualified URLs to github in the READM.md files, this is already a pattern in some hint/packages.
Fixes #3792 
Closes #3937
=> Docs: Fix broken README.md links on npmjs.org

packages/hint-axe/README.md, packages/hint-axe/scripts/create/create-docs.js
Make sure you:
hint-axe docs are now generated (#3418) at build time so the relative path is only good for post build local install of the repository and results in 404s for anyone browsing github or npmjs.org (the more common scenario).
To give the best experience for the more common scenario this change directs the links to webhint.io which will have the information from the latest release.
Follows up #3937
=> Docs: Fix broken hint-axe README.md links

azure-pipelines/all-versions.yml, azure-pipelines/latest-version.yml
Make sure you:
Windows is timing out a lot lately, this PR will increase the CI timeout to 120 minutes.
=> Fix: Increase build timeout to allow windows pass the tests

packages/hint-compat-api/docs/html.md, packages/hint-compat-api/src/html.ts, packages/hint-compat-api/tests/fixtures/html/ignore.html
Make sure you:
This is covered with more nuance by `hint-disown-opener`.
No need to duplicate reporting in `hint-compat-api/html`.
=> New: Ignore a[rel=noopener] by default

packages/formatter-html/package.json, packages/formatter-html/src/result.ts, yarn.lock
Fix #4044
Make sure you:
This removes `moment` as a dependency. It's tempting to replace it with another time/date library, however the only function `moment` was used in is simple enough that I don't believe it justifies pulling in another dependency!
=> Chore: Remove `moment` as a dependency

packages/hint-ie-flexbox-compat/.npmrc, packages/hint-ie-flexbox-compat/LICENSE.txt, packages/hint-ie-flexbox-compat/README.md, packages/hint-ie-flexbox-compat/package.json, packages/hint-ie-flexbox-compat/src/_locales/en/messages.json, packages/hint-ie-flexbox-compat/src/hint.ts, packages/hint-ie-flexbox-compat/src/meta.ts, packages/hint-ie-flexbox-compat/tests/fixtures/inline.css, packages/hint-ie-flexbox-compat/tests/fixtures/keyframe-rule.css, packages/hint-ie-flexbox-compat/tests/fixtures/multiple-displays-in-rule.css, packages/hint-ie-flexbox-compat/tests/fixtures/multiple-displays.css, packages/hint-ie-flexbox-compat/tests/fixtures/no-flex.css, packages/hint-ie-flexbox-compat/tests/fixtures/simple.css, packages/hint-ie-flexbox-compat/tests/tests.ts, packages/hint-ie-flexbox-compat/tsconfig.json
This is an attempt to address #4072.
A hint that warns users when they do configure IE as a target browser and flexbox is used in one of the stylesheets.
This is mostly to get the ball rolling and gather feedback.
Let me know what you think.
=> New IE flexbox compat hint

packages/connector-puppeteer/src/lib/lifecycle.ts
Fix #4089
Make sure you:
Detach mode is used mostly for the test runner, to avoid opening multiple instances of the browser. To do so, it store in disk the browser information of the first instance opened, so the next calls can reuse that information.
Before this PR, the writing/reading of the disk were done even if it wasn't running in detach mode.
This PR disables the writings to disk if we are not in detach mode. This will save some time accessing to disk, but more important, it will solve a problem running `connector-puppeteer` in Azure Functions Consumption plan.
Azure Function Consumption plan doesn't allow writing in the disk, except for the tmp folder, so this change is needed if we want to complete …
=> Chore: Connector puppeteer use lock only in detached mode

.markdownlintrc, packages/hint/docs/user-guide/concepts/hints.md, packages/hint/docs/user-guide/configuring-webhint/summary.md
Make sure you:
`markdownlint` is configured to break lines that are too long. This includes table rows, which causes the content after the line-break to start a new table row.
This PR enables the `markdownlint` configuration flag to ignore line-length for table rows.
----
----
----
=> Docs: Fix broken table rows and related lint rule

packages/connector-puppeteer/src/connector.ts, packages/connector-puppeteer/src/lib/lifecycle.ts
=> Fix: Check detach mode in close method

packages/hint-validate-set-cookie-header/src/hint.ts
Make sure you:
Work around a Firefox bug where a date separated by dashes results
in a negative year. Corrects the negative year to match the behavior
of other browsers while leaving other invalid dates unchanged.
Fix #4209
=> Fix: Incorrect recommended expires date

packages/connector-local/src/connector.ts, packages/connector-local/tests/fixtures/folder with spaces and [brackets]/script with spaces and [brackets].js, packages/connector-local/tests/tests.ts, packages/utils-network/src/as-path-string.ts, packages/utils-network/tests/as-path-string.ts
Make sure you:
Local connector normalizes paths by converting all paths to URIs
with file protocol which encodes URI reserved characters
(e.g. " space " and [brackets]). This is done with `encodeURI` in
[`file-url`][1] called on packages/utils-network/src/as-uri.ts:49.
The encoded URI pathnames are then passed to the OS and not found:
file:///mnt/[id]/script.js -> (`encodeURI`)
-> file:///mnt/%5Bid%5D/script.js -> /mnt/%5Bid%5D/script.js
Decode file protocol pathnames:
/mnt/%5Bid%5D/script.js -> (`decodeURI`) -> /mnt/[id]/script.js
This is the same problem as #3401 which solved the problem of %20 with
string replace in #3409, because `decodeURI` handles all URI encodings
I reverted those lines.
This fix has been tested against:
- …
=> Fix: Support for URI reserved characters in paths

packages/hint-http-cache/src/meta.ts, packages/hint-http-compression/src/meta.ts, packages/hint-https-only/src/meta.ts, packages/hint-minified-js/package.json, packages/hint-minified-js/src/meta.ts, packages/hint-minified-js/tests/tests.ts, packages/hint-no-disallowed-headers/src/meta.ts, packages/hint-performance-budget/src/meta.ts, packages/hint-sri/src/meta.ts, packages/hint-ssllabs/package.json, packages/hint-ssllabs/src/meta.ts, packages/hint-strict-transport-security/src/meta.ts, packages/hint-x-content-type-options/src/meta.ts, packages/hint/docs/user-guide/configuring-webhint/ignoring-domains.md, packages/hint/src/lib/engine.ts, packages/hint/src/lib/types/hint-meta.ts, packages/utils-network/README.md, packages/utils-network/src/index.ts, packages/utils-network/src/rx-localhost.ts, packages/utils-network/tests/rx-localhost.ts, packages/utils-tests-helpers/src/hint-runner.ts, packages/utils-worker/tests/helpers/runner.ts
Make sure you:
Extends the metadata available to hints to include an `ignoredUrls` field, allowing a set
of default ignored URLs to be specified for a given hint. This default value is ignored
whenever any explicit `ignoredUrls` are specified for that hint in `.hintrc`.
Updates a collection of hints (largely related to HTTP headers) to ignore localhost and
127.0.0.1 URLs by default to avoid false-positives during local development.
Fix #4229
=> Fix: Avoid false-positives on localhost

packages/hint/docs/user-guide/index.md
it is not clear or documented anywhere that a local file path is an option as argument to the path parameter.
cli _help_ scheme, as well, implies the last argument to be a url (`hint [options] https://url.com`).
as only starting to use webhint cli I had this only clarified in a response in the gitter channel
Make sure you:
=> [Docs] Adds clarification in user-guide documentation

packages/configuration-development/index.json, packages/configuration-development/package.json, packages/configuration-web-recommended/index.json, packages/configuration-web-recommended/package.json, packages/extension-browser/package.json, packages/extension-browser/tsconfig.json, packages/hint-no-inline-styles/package.json, packages/hint-no-inline-styles/src/hint.ts, packages/hint-no-inline-styles/src/meta.ts, packages/hint-no-inline-styles/tests/test.ts, packages/utils-worker/package.json
=> Chore: Add no-inline-styles hint to default configurations

packages/hint-typescript-config/src/import-helpers.ts
Make sure you:
Change pathToTslib to resolve the path to tslib based on the tsconfig.json location rather than current working directory. Fixes #4175.
=> Fix: Discover tslib in projects with nested structure

packages/hint/docs/user-guide/index.md
The `npm` short alias for the `install` command is `npm i`.
=> Docs: Fix npm short alias for install command

packages/extension-browser/package.json, packages/hint-compat-api/tests/utils/browsers.ts, packages/utils-compat-data/README.md, packages/utils-compat-data/package.json, packages/utils-compat-data/scripts/mdn-browser-compat-data.js, packages/utils-compat-data/scripts/mdn-data.js, packages/utils-compat-data/src/browsers.ts, packages/utils-compat-data/src/css.ts, packages/utils-compat-data/src/helpers.ts, packages/utils-compat-data/src/html.ts, packages/utils-compat-data/tests/browsers.ts, packages/utils-worker/package.json, yarn.lock
Make sure you:
Updated dependency mdn-browser-compat-data from 1.1.2 to version 2 according to https://github.com/mdn/browser-compat-data/blob/v1.1.2/UPGRADE-2.0.x.md, and without any more necessary changes to version 3 (3.2.0 actually)
The change is necessary as the package has been renamed, see the following message on the shell:
> npm WARN deprecated mdn-browser-compat-data@1.1.2: mdn-browser-compat-data is deprecated. Upgrade to @mdn/browser-compat-data. Learn more: https://github.com/mdn/browser-compat-data/blob/v1.1.2/UPGRADE-2.0.x.md
Closes #4117
=> refactor: updated dependency mdn-browser-compat-data

packages/hint-compat-api/docs/html.md, packages/hint-compat-api/src/html.ts, packages/hint-compat-api/tests/fixtures/html/ignore.html
Make sure you:
Fix for issue https://github.com/webhintio/hint/issues/4547 to allow ignoring of `inputmode` attribute in `input` elements. While Safari and Firefox do not support the attribute, it is still useful in other browsers, thus should not trigger a hint.
=> Fix: Ignore input[inputmode]

packages/utils-network/package.json, packages/utils-network/src/as-uri.ts, yarn.lock
Make sure you:
The 'file-url' dependency has switched to ESM making it harder to import and use until all of webhint is switched to ESM. Examining the usage of this dependency in webhint revealed it wasn't really needed as the paths being processed are already ensured to be absolute and can simply be prefixed with `file://`.
Closes #4469
=> Chore: Remove file-url in favor of simpler inline logic

packages/hint-axe/src/util/axe.ts
Make sure you:
Interestingly axe-core can return an array of selectors for a target
instead of just a single string (contrary to the definitions in axe.d.ts).
This was causing problems when the array was passed down to
webhint's selectors library.
Fixed by checking if the target selector is an array, and if so,
using the first selector to find the element.
Fix #4834
=> Fix: Handle multiple selectors from axe-core

packages/configuration-development/index.json, packages/hint-typescript-config/docs/no-comments.md
Make sure you:
Disable the hint `typescript-config/no-comments` by default per
feedback from the TypeScript team in #4839. Also update docs
to indicate the hint is disabled.
Fix #4839
=> New: Disable typescript-config/no-comments by default

packages/parser-jsx/src/parser.ts, packages/parser-jsx/tests/tests.ts
Make sure you:
Normally JSX expressions are translated to text nodes to ensure
elements are considered as having content (and labels). However,
not all HTML elements allow text children, so in these cases the
expression is now omitted from the JSX-to-HTML conversion.
This replaces an earlier fix for `<ul>` where a wrapper `<li>`
was added instead. The new approach is preferred because it
still produces valid output while being more similar to the
original source code.
Fix #4878
=> Fix: Omit JSX expressions in non-text HTML parents

packages/parser-jsx/src/parser.ts, packages/parser-jsx/tests/tests.ts, packages/utils-dom/src/create-html-document.ts, packages/utils-dom/src/htmldocument.ts, packages/utils-dom/src/utils.ts, packages/utils-dom/tests/axe.ts, packages/utils-dom/tests/html.ts, packages/utils-dom/tests/htmldocument.ts, packages/utils-dom/tests/node.ts
Make sure you:
Prevent false-positives when processing root elements like `<li>` in
template fragments by assuming and creating expected parent elements
so hints see the most likely fully-realized structure.
Fix #4868
=> Fix: Assume expected parents in template fragments

packages/hint-http-cache/src/meta.ts, packages/hint-http-compression/src/meta.ts, packages/hint-https-only/src/meta.ts, packages/hint-minified-js/src/meta.ts, packages/hint-no-disallowed-headers/src/meta.ts, packages/hint-performance-budget/src/meta.ts, packages/hint-sri/src/meta.ts, packages/hint-ssllabs/src/meta.ts, packages/hint-strict-transport-security/src/meta.ts, packages/hint-x-content-type-options/src/meta.ts, packages/utils-network/README.md, packages/utils-network/src/index.ts, packages/utils-network/src/rx-local-file.ts, packages/utils-network/tests/rx-local-file.ts
Make sure you:
This PR mirrors the changes in https://github.com/webhintio/hint/pull/4234/files in order to disable non applicable hints (like perf and security) for pages loaded from local files.
=> Fix: Add regex to disable header hints for local files

packages/connector-puppeteer/tests/request-response.ts
Make sure you:
In CI all tests are headless, but locally most run showing the
browser UI. This caused getFavIcon to not be called as it's only
needed when running in headless mode. This in turn caused branch
coverage to be just short of our 80% goal when running locally.
Fixed by ensuring at least one test runs in headless mode even
locally so this branch of code is executed.
=> Chore: Fix test coverage issue by ensuring one test is headless

packages/hint-no-vulnerable-javascript-libraries/package.json, packages/hint-no-vulnerable-javascript-libraries/scripts/pack-snyk.js
Make sure you:
Changes the step which prunes the data included in the snapshot
to output directly to the dist folder instead of src folder.
Also updates the copy step to avoid copying the original
snapshot to dist.
This fixes the pruning step from updating the tracked original
file which was resulting in diffs in git (and occasionally made
it into PRs).
=> Fix: Avoid changing original snyk-snapshot.json on build

packages/hint-axe/scripts/create/utils.js, packages/hint-axe/tests/text-alternatives.ts
Make sure you:
Disabled due to false positives in jsdom.
Fix #5030
=> Chore: Disable axe-core svg-img-alt rule by default

packages/extension-vscode/src/server.ts
Make sure you:
Fixes an issue with webhint picking up internal VS Code settings and
configuration files, then failing when the URL scheme doesn't appear
local. Since these files shouldn't be analyzed, inputs are now filtered
to only scan URLs explicitly referencing local files (`file://`).
Ref microsoft/vscode-edge-devtools#910
=> Fix: Ignore internal VS Code files

packages/extension-vscode/src/utils/webhint-packages.ts
The `hint` package treats `@hint/configuration-development` as an
optional dependency which means npm can choose to ignore it if there
are issues during install. However, when using the VS Code extension
this configuration is expected to exist, leading to errors in the
extension if it is not present.
Fixed by explicitly requesting the package for this configuration
in addition to `hint` when installing the shared webhint instance.
=> Fix: Ensure development configuration is installed

packages/extension-vscode/src/utils/process.ts
Make sure you:
Aligns behavior for updates on Windows with other OSes.
Ref microsoft/vscode-edge-devtools#976
=> Fix: Hide console when updating hint on Windows

packages/utils-dom/src/cssstyledeclaration.ts, packages/utils-dom/src/node.ts, packages/utils-dom/tests/axe.ts
Make sure you:
Fixes internal axe-core errors in `isVisible` when incorrectly
calling `getAttribute` on a document node. Similarly fixes
axe-core errors calling `match` on the return value of
`getProperty` which needed to be the empty string when
no match exists. Both of these issues were causing results
to be omitted for the `label` rule in certain circumstances.
Also enhances the test helpers to allow passing a list of
tests to validate for each axe-rule (instead of just one pass/fail).
=> Fix: Add Node enums required by axe-core

packages/extension-vscode/src/utils/webhint-packages.ts
Make sure you:
Writes a timestamp after a successful check for updates.
Validates timestamp is older than 24 hours before checking again.
=> Chore: Throttle 'hint' update checks to once a day

packages/hint-no-disallowed-headers/README.md, packages/hint-no-disallowed-headers/src/_locales/en/messages.json, packages/hint-no-disallowed-headers/src/hint.ts, packages/hint-no-disallowed-headers/tests/tests.ts
Make sure you:
This PR removes the Via header from the list of disallowed headers in the `hint-no-disallowed-headers` package. The tests are updated to ensure that including this header does **not** produce any report. The list of disallowed headers is also updated in the README file.
Fixes #5159
=> Fix: Remove reports for Via HTTP Header

packages/hint-axe/package.json, packages/hint-axe/tests/fixtures/forms.jsx, packages/hint-axe/tests/fixtures/spread.jsx, packages/hint-axe/tests/forms.ts, packages/hint-axe/tsconfig.json, packages/hint-button-type/src/hint.ts, packages/hint-button-type/tests/tests.ts, packages/parser-jsx/src/parser.ts, packages/parser-jsx/tests/tests.ts, packages/utils-dom/src/htmlelement.ts, packages/utils-dom/tests/htmlelement.ts
Make sure you:
Introduces a placeholder for `{...spread}` in the transformed HTML along
with a `utils-dom` helper to identify whether additional, unknown attributes
may be present. Uses this helper in `hint-button-type` to avoid triggering
a false-positive.
Also updates JSX-to-HTML conversion to assume a `title` attribute when
`{...spread}` is present if not already set. This ensures a label is provided
for any transformed element with spread, avoiding false-positives in
`hint-axe`.
Fix #5166
Fix microsoft/vscode-edge-devtools/issues/1031
=> Fix: Avoid false positives when using {...spread} in JSX

packages/configuration-accessibility/index.json, packages/hint-axe/scripts/create/create-config.js
Make sure you:
Align the format of `configuration-accessibility` with other webhint default
configurations. Specifically this updates the configuration to avoid specifying
an explicit severity, allowing the severity to be determined per-report based
on the underlying `axe-core` impact.
=> Fix: Respect default severity for a11y hints

packages/extension-browser/package.json, packages/extension-browser/tests/end-to-end.ts, packages/extension-browser/webpack.config.js, packages/hint-axe/package.json, packages/hint-axe/src/util/axe.ts, packages/hint-axe/tsconfig.json, packages/hint/src/lib/types/events.ts, packages/utils-dom/src/traverse.ts, packages/utils-fs/src/load-js-file.ts, packages/utils-worker/package.json, packages/utils-worker/src/connector.ts, packages/utils-worker/webpack.config.js, packages/utils/src/packages/load-resource.ts, packages/utils/src/packages/require-package.ts
Make sure you:
1. Replace `eval('require')` calls specific to webpack with `__non_webpack_require__`
2. Import `axe-core` directly instead of loading as a string
a. Continues to allow evaluation in `connector-puppeteer` and similar via `axe.source`
b. Enables direct execution in `utils-worker` via `axe.run`
=> Chore: Remove usage of eval from utils-worker

packages/utils-json/.gitignore, packages/utils-json/src/export-require.ts, packages/utils-json/src/final-config.ts, packages/utils-json/src/types.ts, packages/utils-json/tests/final-config.ts, packages/utils-json/tests/fixtures/baseConfig.json, packages/utils-json/tests/fixtures/baseConfigCircular.json, packages/utils-json/tests/fixtures/node_modules/@tsconfig/strictest/tsconfig.json
Make sure you:
Fix behavior in final-config where path resolution was done by
using path.resolve instead of require.resolve. This allows NodeJS
fallback behavior when searching for a module
Fix #5169
=> Fix: Allow Node.js style resolution in config #5192

packages/parser-jsx/src/parser.ts
Make sure you:
Lines are 1-based in the JS AST, but columns are 0-based.
We need both to be 1-based in the parse5 HTML AST, this
was already special-cased for the start tag, but needed to be
applied for all column positions.
=> Fix: Off-by-one issue with JSX column locations

packages/hint-css-prefix-order/tests/fixtures/prefixes-last-webkit.fixed.html, packages/hint-css-prefix-order/tests/tests.ts, packages/hint/src/lib/hint-context.ts, packages/utils-dom/src/htmlelement.ts
Make sure you:
Updates `context.report` to adjust any provided `fixes` by the location
of the provided `element` if the `codeLanguage` is anything other
than `html` (meaning it is embedded).
Also fixes `element.getContentLocation` to include adjusting the
end location of the provided offset (if present) to ensure the full
range is adjusted and not just the start.
Lastly adds a new test case for `hint-css-prefix-order` to verify
fixes are applied correctly for CSS in HTML.
=> Fix: Adjust fix locations for embedded languages, e.g. CSS in HTML

packages/extension-vscode/.npmignore, packages/extension-vscode/src/quickfix-provider.ts
Make sure you:
- [ x] Signed the Contributor License Agreement (after creating PR)
- [ x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)
- [ x] Added/Updated related documentation.
- [x ] Added/Updated related tests.
Latest `npm` extension-vscode package does not include the dist folder which breaks the extension. 
This seems to be caused by the `.gitignore` on the upper level folder, solution is to create a `.npmignore `
which overrides `.gitignore` configuration when publishing on `npm`
=> Fix: Fixes an issue were dist folder was being ignored in extension-vscode.

packages/hint-axe/package.json, packages/hint-axe/src/util/axe.ts, packages/hint-axe/tests/fixtures/local-default-iframe.html, packages/hint-axe/tests/language.ts, packages/hint-axe/tsconfig.json, packages/utils-worker/package.json
Make sure you:
Fixes an issue where axe-core throws:
`allowedOrigins value "null" is not a valid origin`
This is due to a axe-core throwing an error instead of finishing the analysis, this is currently an open bug in dequelabs:
`dequelabs/axe-core`
`issue: 3002`
This only manifests under the following conditions:
- local `html` files only
- file has iframes
- the iframes have the `Default` CSP
- The exception gets bubbled and eventually crashes `webhint`. To avoid this the proposed fix is to not scan `iframes` for local `html` files.
-----
Fix #5285
=> Fix: Axe-core throws errors with local iframes

packages/utils-dom/src/htmlelement.ts
Make sure you:
Removes a `console.log` tracing element left from previous work. This was causing a lot of noise in the console and was making analysis slower.
Fix: #5329
=> Fix: Remove tracing in htmlelement

packages/hint/src/lib/hint-context.ts, packages/utils-dom/src/htmlelement.ts, packages/utils-worker/tests/integration.ts
Make sure you:
Pull request #5261 inadvertently removed the `elementId` from the returned location returned by `findProblemLocation`. This PR reintroduces it.
=> Fix: Re-adding elementId to location(hint-context)

packages/hint-no-broken-links/tests/tests.ts
Make sure you:
PR #5317 provided a fix for a broken behavior on`broken-links-package`: 
- A `http` behavior with valid `https` links was being marked as as a `broken-link`. 
This PR provides a test to avoid regressing the behavior in the future.
=> Chore: Test for regressed broken-links-package.

package.json, yarn.lock
Make sure you:
Updates the json5 version to 4.1.2 to address a security update.
=> Update: Bumps json5 version

packages/extension-browser/package.json, packages/extension-browser/scripts/bundle-size.js
Make sure you:
Fixing an issue between the latest version of glob (8) and windows paths. Starting on V8 glob only support forward paths, which `path.resolve` was failing to return. Fix was to replace the characters and standardize the path.
=> Fix: Issue with glob latest version and windows

packages/hint-no-vulnerable-javascript-libraries/package.json, yarn.lock
Make sure you:
A dependency in `hint/fix-no-vulnerable-javascript-libraries` changed URL and was timing out, I had to point to a more recent url.
=> Fix: Replacing url for a knockout dependency

packages/extension-browser/package.json, packages/hint-detect-css-reflows/src/_locales/en/messages.json, packages/hint-detect-css-reflows/src/composite.ts, packages/hint-detect-css-reflows/src/layout.ts, packages/hint-detect-css-reflows/src/paint.ts, packages/hint-detect-css-reflows/tests/composite.ts, packages/hint-detect-css-reflows/tests/layout.ts, packages/hint-detect-css-reflows/tests/paint.ts, packages/utils-worker/package.json, packages/utils-worker/tsconfig.json
Make sure you:
- Changing the way CSSReflow.json is loaded in favor of require instead of loading the loadJSONFile
- Passing codeSnippet to the returned hint
- Rising the size limit on some packages as they are on the limit of size which can case issues with updates.
=> Chore: Adding `hint-detect-css-reflows` to `utils-worker` 

packages/hint-detect-css-reflows/README.md, packages/hint-detect-css-reflows/docs/composite.md, packages/hint-detect-css-reflows/docs/layout.md, packages/hint-detect-css-reflows/docs/paint.md, packages/hint-detect-css-reflows/src/composite.ts, packages/hint-detect-css-reflows/src/layout.ts, packages/hint-detect-css-reflows/src/meta/composite.ts, packages/hint-detect-css-reflows/src/meta/layout.ts, packages/hint-detect-css-reflows/src/meta/paint.ts, packages/hint-detect-css-reflows/src/paint.ts
Make sure you:
Some of the meta files and docs had the incorrect prefix `hint-` in the name, although this is correct
in some parts of the code, others do not expect it to be in that format like `utils-worker` so I'm renaming them.
=> Chore: Fix `detect-css-reflows` in meta and docs.

packages/parser-css/package.json, packages/parser-css/src/parser.ts, packages/parser-css/tsconfig.json
Make sure you:
Makes `parser-css` less noisy for regular users by changing the logger to debug only. Also adapts the error message to something more meaningful.
=> Chore: makes `parser-css` verbose on debug only

packages/hint-detect-css-reflows/README.md, packages/hint-detect-css-reflows/src/_locales/en/messages.json, packages/hint-detect-css-reflows/src/composite.ts, packages/hint-detect-css-reflows/src/layout.ts, packages/hint-detect-css-reflows/src/paint.ts, packages/hint-detect-css-reflows/tests/composite.ts, packages/hint-detect-css-reflows/tests/fixtures/composite-triggers.css, packages/hint-detect-css-reflows/tests/fixtures/layout-triggers.css, packages/hint-detect-css-reflows/tests/fixtures/paint-triggers.css, packages/hint-detect-css-reflows/tests/layout.ts, packages/hint-detect-css-reflows/tests/paint.ts
Make sure you:
This PR modifies the `hint-detect-css-reflows` to be scoped only to properties inside `@keyframes` as it is where the `Layout` and `Paint` can become a factor for jankiness or slow animations
=> Fix: Scoping `detect-css-reflows` to animations

package.json, packages/connector-puppeteer/package.json, packages/utils-connector-tools/package.json, packages/utils-network/package.json, yarn.lock
Make sure you:
This PR revert back node version to v2 as v3 requires ESM.
=> Fix: Reverting node-fetch to v2

.github/ISSUE_TEMPLATE.md, README.md, packages/hint/README.md
Make sure you:
- **N/A** Added/Updated related documentation.
- **N/A** Added/Updated related tests.
After [fixing CLA links pointing to a non-existent subdomain of `js.foundation`](https://github.com/webhintio/hint/pull/5691), wondered if there are any other `js.foundation` links that don't work anymore. And found out the Code of Conduct doesn't point to the document but to the OpenJS Foundation main site. Fixing it by pointing to the OpenJS Foundation Code of Conduct (found the link by grabbing it from their website's "Code of Conduct" item in the "About" dropdown).
Replaced the one in the README as this one seems more canonical than a markdown document in a GitHub repo
=> Docs: Update links to OpenJS Foundation CoC

README.md, packages/hint/docs/about/FAQ.md
Make sure you:
- **N/A** Added/Updated related documentation.
- **N/A** Added/Updated related tests.
Online scanner [is not available anymore](https://github.com/webhintio/webhintio.github.io/issues/989#issuecomment-940397677) so removing references to it in docs.
Relates to https://github.com/webhintio/webhintio.github.io/issues/989
Did `grep -r 'scanner' .` and found those occurrences relating to the web scanner only :)
=> Docs: Remove references to retired online scanner

packages/hint/docs/user-guide/index.md
Seems like this was a bit outdated hint does not run on node 12
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'hint@7.1.10',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
```
Make sure you:
=> Update minimum node version to 14

packages/hint-http-cache/src/hint.ts
Make sure you:
``parseCacheControlHeader()`` now treats ``stale-while-revalidate`` and ``stale-if-error`` directives with value as valid directives.
They should be, according to [rfc5861](https://datatracker.ietf.org/doc/html/rfc5861).
=> stale-while-revalidate and stale-if-error caching directives are valid with value

packages/utils-worker/package.json, packages/utils-worker/webpack.config.js, yarn.lock
Make sure you:
Fixing "...emit for this file requires using private name 'Context'", caused by the inclusion of VM polyfill. Switching it off instead.
=> Fix: Fixing "...emit for this file requires using private name 'Context'"

package.json
Make sure you:
Disables `markdown-link-validator` as part of the `lint:md` step. It seems that it does not meet it's original purpose anymore, which to my understanding, is to keep a clean ecosystem with working links. `markdown-link-validator` only runs when the file is checked-in or changed but those links can expire between these times. At the moment of writing this there are more than 50 expired links, so I think is better to run it as a scheduled action.
=> Chore: Disable lint-markdown-validator

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
Make sure you:
- **N/A** Added/Updated related documentation.
- **N/A** Added/Updated related tests.
- Update of https://github.com/webhintio/hint/pull/5691 with new link
After looking for the CLA in docs for my [first contribution](https://github.com/webhintio/hint/pull/5690) found out the only reference to it had a link that didn't work (domain doesn't exist). Fixing that link + adding a link in PR template so impatient contributors like me can browse the CLA whilst the CLA signing comment appears.
=> Docs: Update CLA link and add it in PR template

packages/extension-browser/package.json, packages/hint-compat-api/tests/css.ts, packages/hint-compat-api/tests/fixtures/html/elements.html, packages/hint-compat-api/tests/html.ts, packages/utils-compat-data/package.json, packages/utils-compat-data/scripts/extra-data.js, packages/utils-compat-data/scripts/mdn-browser-compat-data.js, packages/utils-compat-data/scripts/mdn-data.js, packages/utils-compat-data/src/browsers.ts, packages/utils-compat-data/src/css.ts, packages/utils-compat-data/src/helpers.ts, packages/utils-compat-data/src/html.ts, packages/utils-compat-data/src/matches.ts, packages/utils-compat-data/tests/browsers.ts, packages/utils-worker/package.json, yarn.lock
Make sure you:
Updates `mdn-data` to latest version `2.6.1` and `@mdn/browser-compat-data` to `5.5.23` (latest). It also updaets the test and dependencies to be able to work with this latest update.
Close #5824
=>  Upgrade: Bump @mdn/browser-compat-data from 4.1.10 to 5.5.23

package.json, packages/utils-compat-data/tests/support.ts, yarn.lock
Make sure you:
There were a couple of version of `@mdn/browser-compat-data` due to a indirect reference, this PR forces all dependencies to be on the same version. 
Fixes #5723
=> Fix: Forcing resolution of mdn/browser-compat-data on package.json

packages/utils/package.json, yarn.lock
Make sure you:
Upgrade: Bump fast-xml-parser to 4.1.3
=> Upgrade: Bump fast-xml-parser to 4.1.3

packages/hint-axe/src/util/axe.ts
Make sure you:
Sometimes axe would report an issue but not provide an HTML snippet for where the issue was found in the HTML document
=> Fix an issue where axe would not provide an html snippet - Fixes #5835
